### PR TITLE
Issue 1197 jython slow

### PR DESCRIPTION
**Pull request by berryma4**
#1197

### CODE REVIEW

**Comment by berryma4** [comment]
@shroffk @kasemir @jbobnar 
Please check that this doesn't break your existing screens.
This upgrades to jython 2.7.0 and changes the new PythonInterpreter to threadLocalStateInterpreter in BOY.

**Comment by kasemir** [comment]
I haven't rebuilt everything to get jython 2.7.0. I did check the opibuilder updates (threadLocalStateInterpreter) and it looks good. Kunal's very slow example is fixed, and the SNS displays that I checked are OK as well.

**Comment by jbobnar** [comment]
I think there are two (potential) issues:
1. The synchronization in JythonInit#getInstance is not done properly. If two threads request the first instance at the same time, you'll end up doing the same initialization twice.
2. I didn't look into details, but Py.getSystemState seems like a shared instance among all interpreters on the same thread. If that is true it probably shouldn't be closed and cleaned (in dispose method)?

**Comment by kasemir** [comment]
You're right on the init. Making the whole call synced would help. .. Except it is (unfortunately) called on the UI thread, so in practice no difference.

I understand the threadLocalStateInterpreter to return a new interpreter, 
http://www.jython.org/javadoc/org/python/util/PythonInterpreter.html#threadLocalStateInterpreter(org.python.core.PyObject)
Closing it seems OK.

**Comment by jbobnar** [comment]
Perhaps the initialization could be done during plugin activation in a background thread?

**Comment by kasemir** [comment]
Jaka, you're right about performing the init once, in background, on startup, if possible. Kunal, Eric and I had discussed the multiplicity a bit. Originally, each script invocation created its own interpreter and context for variables. With the jython update, the interpreter initialization time suddenly went way up, and one interpreter per script is really a lot. Then Eric went to just one interpreter for all. Much faster, but probably bad because now a script invoked in screen B would see vars created by another script in screen A. There could also be a problem with longer running scripts that spawned threads and access the 'widget' var, which is set to the current widget on each script invocation. Having one interpreter per display seems a good balance. This would even allow a script run on display startup to set variables and later running scripts within the same display can then access them. Would need to be aware of 'widget' changing, though. Way into the future, scripts should run in the background. Scripts for multiple widgets should run in parallel, so they need to implement something like a 'run(widget, pvs)' method that is invoked with the current parameters. Setting those as global vars won't work.

**Comment by berryma4** [comment]
There is really no point to JythonInit with the current threadLocalStateInterpreter, so I removed it.  But, you're right, with this and pvmanager having the lazy load, the first screen takes a little long.

**Pull request merged**
