### PR TITLE
Diirt integration

### PR DESCRIPTION
**Pull request by shroffk**
Preliminary set of changes for diirt 3 integration
@arnaudf-iter @kasemir @willrogers @berryma4

### CODE REVIEW

**Comment by shroffk** [comment]
In addition to the diirt 3 I have also tried to fix references to third part libraries like (javax, jdbc for mysql,..) to use the one provided by orbits.
In terms of dependencies, I have preferred the use of imported packages to required plug-ins to allow us some flexibility with the migration.

**Comment by shroffk** [comment]
Note: There isn't a specific target definition file associated with this branch, the following chnages have been tested by building the diirt3 p2 repo locally and using it via the composite repository mvn property.

**Comment by willrogers** [comment]
I find three problems when building:

* `org.csstudio.core.diirt.feature` can't find `datasource-timecache` for some reason - it's not getting built into the diirt p2 repo
* `org.csstudio.scan.server` still has references to `org.epics.vtype`
* `org.csstudio.simplepv.pvmanager.test` calls `CompositeDataSource.setDefaultDataSource()`, which no longer exists

Having said that, I still don't know how to configure OPIBuilder to connect to PVs when it is built.

**Comment by willrogers** [comment]
That fixed problems one and two.  I still need to comment `org.csstudio.simplepv.pvmanager.test` to get Maven to build.

**Comment by willrogers** [comment]
OK I built our product (including `org.csstudio.core.diirt.feature`) and followed the instructions [here](https://github.com/diirt/diirt/wiki/Diirt-Configuration) to configure it.  It works exactly as you'd expect.

**Comment by shroffk** [comment]
Ok, that is some good news.
Did you try to change the configuration folder or are you using the default one which points to the user home directory.

TODO:
- [ ] Clean up the preference/property mapping for the diirt home folder.
- [ ] Put together a set of instructions about all the different ways we can configure diirt and what is the priority

**Comment by willrogers** [comment]
I created a specific directory and used the preference to point to that directory.  I did get a couple of exceptions when the directory didn't exist.  I'm not sure if that's just teething problems.

**Comment by berryma4** [comment]
#1171

**Pull request merged**
