### PR TITLE
Alarm table

### PR DESCRIPTION
**Pull request by jbobnar**
Added only the missing comparators (the problematic severity icon comparator is not in this pull request).
Updated the icons loading, and added the disabled icons, which will be needed for blinking.
Improved the looks of the alarm tree icons using antialiasing and transparency.

### CODE REVIEW

**Comment by berryma4** [comment]
@kasemir can you check, thank you!

**Comment by berryma4** [comment]
ok to test

**Comment by kasemir** [comment]
I looked through the code changes, and it mostly appears good.
Still, I'd like to actually try it when back from the EPICS meeting, i.e. early next week.

**Comment by kasemir** [comment]
Fine with me, but may require an update to get over the merge conflict.

**Comment by jbobnar** [comment]
Updated this branch from master. There was no conflict.

**Comment by berryma4** [comment]
the checkstyle is giving some eol warnings
https://openepics.ci.cloudbees.com/job/CS-Studio%20-%20Pull%20Request%20-%20Core%20-%20tycho/72/checkstyleResult/new/
Although, Jenkins seems to be re-reporting the same warnings, so the number is off by a multiple.
The checkstyle file is in the cs-studio/build directory.

**Comment by jbobnar** [comment]
@berryma4 I fixed the EOL characters and one trailing whitespace.

**Comment by kasemir** [comment]
Looks like I mistook the merge build checkstyle warnings for merge problems.
Anywho, that's been fixed, so I think we can merge.

**Pull request merged**
