### PR TITLE
Add MinimizeEditor macro to minimize editor when OPI is opened as standalone window.

### PR DESCRIPTION
**Pull request by lcavalli**
See issue #2204.

### CODE REVIEW

**Comment by lcavalli** [comment]
@kasemir, wait merging this pull request. I still have a small issue to fix (see the associated issue #2204 the second time I execute cd-srudio the macro is ignored).

**Comment by berryma4** [comment]
What's the state of this pull request?

**Comment by lcavalli** [comment]
@berryma4, still on hold due to points 2 and 4 of my comment https://github.com/ControlSystemStudio/cs-studio/issues/2204#issuecomment-301270787. I think I can fix point 4, still have to investigate point 2. I will try to find some time to work on this pull request next week (tomorrow in Italy is national holiday).

**Comment by lcavalli** [comment]
This pull request has been superseded by pull request #2272.

**Pull request closed without merging**
