### PR TITLE
Issue1732 java time

### PR DESCRIPTION
**Pull request by kasemir**
#1732
Updates cs-studio to match the diirt Timestamp->Instant update 

Should check if build succeeds for everybody:

 - [x] Diamond
 - [x] SNS: OK with diag.pvfields.test disable, #1733 
 - [x] FRIB
 - [x] NSLS-II

In parallel, diirt needs to merge Issue37-use-java-time into master where some pods datasource was removed from the build to allow it to succeed

### CODE REVIEW

**Comment by willrogers** [comment]
Builds for me if the diirt branch is also merged.

**Comment by berryma4** [comment]
I'm assuming the errors in the build are because diirt needs a pull request merged?
https://travis-ci.org/ControlSystemStudio/cs-studio/builds/121853647
@shroffk

**Comment by willrogers** [comment]
Hold on, we probably need to change the version in the diirt repos in `core/pom.xml` and `applications/pom.xml` from 3.0.3 to 3.1.1.

**Comment by shroffk** [comment]
The diirt master now has been updated with the pods datasource removed.
Once it is confirmed that the diirt master can be build I will release it as 3.1.2
 - [ ] @willrogers 
 - [ ] @kasemir 
 - [ ] @berryma4 
 - [ ] Kunal

**Comment by berryma4** [comment]
@shroffk , Will just changed core and application poms from 3.0.3 to 3.1.1.  Can you update again to 3.1.2 when released.

**Comment by willrogers** [comment]
I get one test failure in diirt: `org.diirt.datasource.file.FileWatcherFileSystemServiceTest.udpateFile()`

It reliably fails using maven and reliably passes using the IDE.

**Comment by berryma4** [comment]
@shroffk were you going to merge:
ControlSystemStudio/diirt#24

**Comment by berryma4** [comment]
I believe we need one more update here, the poms to diirt 3.1.2.  Is it released @shroffk?

**Comment by berryma4** [comment]
sorry @willrogers, I merged without you checking the above box.  I'll leave the branch if you have problems.

**Comment by willrogers** [comment]
OK for me.

**Pull request merged**
