### PR TITLE
Two minor bugfixes in csstudio perspective and databrowser

### PR DESCRIPTION
**Pull request by jbobnar**
CSStudioPerspective: setting the layout via preferences did not work due to incorrect parsing of parameters.
DataBrowser was throwing ArrayIndexOutOfBoundsExceptions when the chart was empty.

### CODE REVIEW

**Comment by kasemir** [comment]
Can you create a ticket for the data browser ArrayIndexOOB issue?

Because of ".. event may come from .. background thread", the pattern
```
if (index < model.getAxisCount())
 {
   final AxisConfig axis = model.getAxis(index);
```
fails when the axes change concurrently.

Something like this would be better:
```
final AxisConfig axis = model.getAxis(index);
if (axis == null)
    return; // Axis no longer valid
```
Might require changes to the model, though, to have getAxis() be thread safe and return null when the index is no longer valid.

**Comment by jbobnar** [comment]
This would not work 
```
final AxisConfig axis = model.getAxis(index);
if (axis == null) ...
```
because the first line (to get axis from the model) already throws an exception. The model needs to be adapted slightly. I'll make an issue and push a commit.

**Comment by kasemir** [comment]
Right, it does require a change to model.getAxis(index).
In there, please avoid synchronize because the underlying array is already a CopyOnWriteArrayList and adding synchronize in one place will then cause FindBugs to require sync. in every place.
Instead, use something like
```
try
{
   return axes.get(index);
}
catch (ArrayIndexOutOfBounds ex)
{
   return null;
}
```

**Comment by jbobnar** [comment]
Bugfix: Issue  #1226

**Comment by kasemir** [comment]
I'm fine with the data browser change, thanks for that.
On the perspective-from-preferences update, Kunal added that, but as far as I can tell the update is good.

**Pull request merged**
