### PR TITLE
o.c.diirt.util.core.preferences: 	Files in diirt home for which no property page exist are copied too (master)

### PR DESCRIPTION
**Pull request by claudio-rosati**
#2134

### CODE REVIEW

**Comment by claudio-rosati** [comment]
@berryma4 can you give it a try?

**Comment by berryma4** [comment]
Thank you!

**Comment by berryma4** [comment]
on project org.csstudio.diirt.util.core.preferences: Unqualified OSGi version 1.0.0.qualifier must match unqualified Maven version 1.0.1-SNAPSHOT for SNAPSHOT builds

**Comment by berryma4** [comment]
I have updated it

**Pull request merged**
