### PR TITLE
Boy set line jump for connectors 1860

### PR DESCRIPTION
**Pull request by rosarp**
Adds line jump for connectors. #1860

### CODE REVIEW

**Comment by kasemir** [comment]
No change. For the display builder, there's currently no plan from our side to invest development time in connectors, let alone ones that approach a schematic design tool with auto-routing.

Compared to BOY, the display builder already has better support for creating and editing the points of plain polylines. If you can place those on top of embedded content in the parent displays, you'll likely achieve the same optical end result in most cases. 

If somebody else wants to implement connector support for the display builder, a requirement would be that the inside of embedded displays (formerly known as Linking Containers) remains a "black box". There won't be any connectors from the inside of one embedded display to the inside of another embedded display, because the embedded content can change, orphaning connector end points. With this in mind I'm worried that `get/setParentDisplayModel` was added to the BOY display model, interlinking the embedded model even further.

Still, I'm OK with this pull request for those who plan to continue using BOY.

**Comment by berryma4** [comment]
I'm not a big fan of adding too many features to BOY, that won't be the direction of the Display Builder. (making conversion and user expectations difficult)

**Comment by kasemir** [comment]
Well, the way linking containers are merged into the overall BOY display model instead of trading them as a black box was, in my opinion, a bad design decision for BOY, but it's there.
ITER stated before that they depend on connectors linking into specific widgets inside linked containers. So we can't remove that from BOY, and ITER is of course allowed to continue to use and maintain BOY. Doesn't mean that a new tool must adopt the same design decision, and nobody is forced to update.

**Comment by berryma4** [comment]
I'm going to squash the merge, so a confined change.

**Pull request merged**
