### PR TITLE
#1058 add some test fragments

### PR DESCRIPTION
**Pull request by richardfearn**
Add new test fragments:

* `org.csstudio.autocomplete.test`
* `org.csstudio.dal.tine.test fragment`
* `org.csstudio.ui.util.test fragment`
* `org.csstudio.utility.test.test`
* `org.csstudio.utility.product.test`
* `org.csstudio.security.ui.test`
* `org.csstudio.logbook.olog.properties.test`
* `org.csstudio.logbook.ui.extra.test`

Test classes moved into source tree in:

* `org.csstudio.alarm.beast.ui.alarmtree`
* `org.csstudio.logbook.viewer`

### CODE REVIEW

**Comment by berryma4** [comment]
#1060

**Comment by berryma4** [comment]
thank you!

**Comment by richardfearn** [comment]
You were too quick... I just realised the issue number in all of the commits was incorrect (#1060 - should have been #1058). Never mind :-)

**Comment by berryma4** [comment]
it's okay, the merge reference is in #1058 ... good enough :)

**Comment by berryma4** [comment]
does this close #1058 or do you have more to move?

**Comment by richardfearn** [comment]
> does this close #1058 or do you have more to move?

There are still 18 to look at...

**Pull request merged**
