### PR TITLE
Update .travis.yml

### PR DESCRIPTION
**Pull request by shroffk**

### CODE REVIEW

**Comment by willrogers** [comment]
Aha @shroffk I think you have the same problem I described in #2640. Do you think it is the same thing?

My manager would now like me to try to resolve this build problem. I would rather eat slugs but there we are.

**Comment by willrogers** [comment]
I have a 'fix' for the Batik problem that allows the build to succeed. Whether it works correctly at runtime is not certain.

This should now be failing on genuine test failures introduced in #2642.

**Comment by shroffk** [comment]
Ok,
Should this be merged?

**Comment by shroffk** [comment]
I was able to recreate the test failures and will look into them tomorrow

**Comment by willrogers** [comment]
I did indeed get a runtime problem. The latest changes do appear to work on the one example of SVGs that I can find, although these widgets are a bit fiddly.

I also fixed the tests.

**Comment by shroffk** [comment]
I know that ITER uses SVGs a lot, can someone from @css-iter test this?

**Comment by shroffk** [comment]
@willrogers can you add your review please

**Pull request merged**
