### PR TITLE
Issue #1470

### PR DESCRIPTION
**Pull request by shroffk**
cleaning up pretune in the app unorganized

### CODE REVIEW

**Comment by berryma4** [comment]
#1470

**Comment by berryma4** [comment]
you may want to add your new feature to the category.xml

**Comment by shroffk** [comment]
well, I am still not sure where else the graphene.opiwidgets are being used...cause those might need a feature too.
Do you know any product that uses o.c.graphene and o.c.graphene.widgets

**Comment by berryma4** [comment]
I use graphene, and graphene.opi, and I made a single feature, o.c.graphene.feature

**Pull request merged**
