### PR TITLE
Import message log based on Elasticsearch.

### PR DESCRIPTION
**Pull request by MichaelRitzert**
#2579 
I folded the view, model and widget into one plugin, but kept the ES client separate since I require this also in other code.

### CODE REVIEW

**Comment by MichaelRitzert** [comment]
It seems there is a problem with the dependencies on org.csstudio.apputil.

**Comment by MichaelRitzert** [comment]
Can I please get a review for this?

**Comment by kasemir** [comment]
Sorry, haven't been involved in this, but as far as I can tell this is about sending the log messages to ES and having a message viewer for it. Shouldn't affect those who don't want to use it.
But there's the build errors, and since this PR was created, the build settings have been changed in the process of moving to Java 9/10/11/12. So before merging it, I think we need to get the build to pass.
Last error I saw was basically `The job exceeded the maximum time limit for jobs, and has been terminated.`, so I've started the build again.

**Comment by MichaelRitzert** [comment]
Still no luck, it seems.

Note: I will create another pull request to master which uses java.net.http and javax.json (which is probably a problem now…), once the build is stable for master. But I will also need this version of code in 4.5.

**Comment by MichaelRitzert** [comment]
Is there anything I can do to get this accepted? The last "error" was "The job exceeded the maximum time limit for jobs, and has been terminated."

**Comment by berryma4** [comment]
I can look at this on Monday for merging.

**Comment by MichaelRitzert** [comment]
Thank you. With the structure of the code settled, I will prepare the corresponding request for master.

**Pull request merged**
