### PR TITLE
Add column Saved TimeSatmp to PVTable 4.1.x

### PR DESCRIPTION
**Pull request by charlesHenryPATARD**
Hello,
We would like to propose a new function to PVTable. The aim of this feature is to add a new column Named TimeStamp Saved wihch saved the column TimeStamp when the Snapshot action is realized.
Do you think it's a good feature ? What's the step by step procedure to create a push stream when the pull request is accepted ?

The feature is already coded. We just wait the green light from you to push it.

Thanks

### CODE REVIEW

**Comment by berryma4** [comment]
I'm little confused with this pull request.  Your feature was on the 4.1.x branch, and hasn't been merge to master yet?

**Comment by charlesHenryPATARD** [comment]
Yes we don’t merged to master. Can you explain to me the step by step process to contribute and push our feature ?

De : Eric Berryman [mailto:notifications@github.com]
Envoyé : jeudi 5 novembre 2015 16:15
À : ControlSystemStudio/cs-studio
Cc : Patard Charles-Henri
Objet : Re: [cs-studio] Add column Saved TimeSatmp to PVTable 4.1.x (#1431)


I'm little confused with this pull request. Your feature was on the 4.1.x branch, and hasn't been merge to master yet?

**Comment by kasemir** [comment]
The basic idea for another timestamp column in the PV table is good.

But this pull request includes changes to some alarm feature, jmsmonitor, scan plugins etc. and should not be merged as is.

Ideally, can you get a copy of the 'master' branch, implement the PVTable changes there, and then have a pull request which includes just those PV table changes?

**Comment by charlesHenryPATARD** [comment]
I make my apologies. I think that my pull request is bad. You can forget this pull request. I need to create a new with just the commits for PVTable from the master.
I will do that tomorrow.

De : kasemir [mailto:notifications@github.com]
Envoyé : jeudi 5 novembre 2015 16:41
À : ControlSystemStudio/cs-studio
Cc : Patard Charles-Henri
Objet : Re: [cs-studio] Add column Saved TimeSatmp to PVTable 4.1.x (#1431)


The basic idea for another timestamp column in the PV table is good.

But this pull request includes changes to some alarm feature, jmsmonitor, scan plugins etc. and should not be merged as is.

Ideally, can you get a copy of the 'master' branch, implement the PVTable changes there, and then have a pull request which includes just those PV table changes?

**Comment by kasemir** [comment]
No worries.

Git may not be helpful in this case when you had worked on a much older copy of the sources and now are trying to get from there to the current 'master', because many directories have been moved around.

I still like git a lot, and http://imgs.xkcd.com/comics/git.png is far too pessimistic, but in this case getting a 'master' clone, then paste your updated PVTable sources in to see what changed might be easier.

**Pull request closed without merging**
