### PR TITLE
2204 tray

### PR DESCRIPTION
**Pull request by willrogers**
@berryma4 @lcavalli this is a pull request that should meet the requirements in #2204.  

The behaviour is as follows:

* When the last window is closed, prompt whether to exit cs-studio or to minimise to system tray
* There is a preference option to remember this choice
* From system tray, you can click and either restore or exit
* There is a preference option to start minimised

Because of our use of standalone windows, we find that people are accidentally closing the main window and losing their standalone windows as well.

In order not to disrupt sites that do not want this behaviour, it is not enabled by default.  In order to enable this behaviour, you need to:

* include in `org.csstudio.core.trayicon.feature` in your product
* extend `org.csstudio.startup.module` and use `org.csstudio.trayicon.TrayWorkbench` as your workbench

```
   <extension
         point="org.csstudio.startup.module">
      <startupParameters
            class="org.csstudio.utility.product.StartupParameters">
      </startupParameters>
      <workspace
            class="org.csstudio.utility.product.WorkspacePrompt">
      </workspace>
      <workbench
            class="org.csstudio.trayicon.TrayWorkbench">
      </workbench>
      <project
            class="org.csstudio.startup.module.defaults.DefaultProject">
      </project>
</extension>
```

### CODE REVIEW

**Comment by lcavalli** [comment]
@willrogers, thanks!

Tried this feature on my product.
I downloaded the github generated diff file, applied and recompiled.
No errors during compilation, but cs-studio doesn't start anymore. This is the relevant part of my .metadata/.log file:

```
!ENTRY org.eclipse.osgi 4 0 2017-08-31 17:26:54.324
!MESSAGE Application error
!STACK 1
java.lang.Exception: Need exactly one workbench extension point, found 0
	at org.csstudio.startup.application.Application.getWorkbenchExtPoint(Application.java:446)
	at org.csstudio.startup.application.Application.startApplication(Application.java:257)
	at org.csstudio.startup.application.Application.start(Application.java:119)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1492)
```

Added
``` <feature id="org.csstudio.core.trayicon.feature"/>```
to features list of repository/cs-studio.product

and used ```org.csstudio.trayicon.TrayWorkbench``` in plugins/org.csstudio.product/plugin.xml

**Comment by willrogers** [comment]
Ouch.  I have the same problem when compiling the generic CS-Studio product.  It works fine in the DLS product.  Let me look at it.

**Comment by willrogers** [comment]
Ah OK.  I missed a step.  You also need to add a dependency on the trayicon plugin to the product manifest.  The full diff is here:

```
diff --git a/plugins/org.csstudio.product/META-INF/MANIFEST.MF b/plugins/org.csstudio.product/META-INF/MANIFEST.MF
index c2e991a..61c822f 100644
--- a/plugins/org.csstudio.product/META-INF/MANIFEST.MF
+++ b/plugins/org.csstudio.product/META-INF/MANIFEST.MF
@@ -18,7 +18,8 @@ Require-Bundle: org.eclipse.ui,
  org.eclipse.ui.ide;bundle-version="3.6.1",
  org.csstudio.ui.menu.app;bundle-version="3.0.0",
  org.csstudio.startup.helper;bundle-version="3.1.0",
- org.csstudio.utility.product;bundle-version="1.1.0"
+ org.csstudio.utility.product;bundle-version="1.1.0",
+ org.csstudio.trayicon;bundle-version="1.0.0"
 Bundle-ActivationPolicy: lazy
 Bundle-RequiredExecutionEnvironment: JavaSE-1.8
 Bundle-Vendor: CS-Studio Collaboration <cs-studio-core@lists.sourceforge.net>
diff --git a/plugins/org.csstudio.product/plugin.xml b/plugins/org.csstudio.product/plugin.xml
index 406bfac..95067f6 100644
--- a/plugins/org.csstudio.product/plugin.xml
+++ b/plugins/org.csstudio.product/plugin.xml
@@ -84,7 +84,7 @@
             class="org.csstudio.utility.product.WorkspacePrompt">
       </workspace>
       <workbench
-            class="org.csstudio.utility.product.Workbench">
+            class="org.csstudio.trayicon.TrayWorkbench">
       </workbench>
       <project
             class="org.csstudio.startup.module.defaults.DefaultProject">
diff --git a/repository/cs-studio.product b/repository/cs-studio.product
index 73e8e70..41cd5e9 100644
--- a/repository/cs-studio.product
+++ b/repository/cs-studio.product
@@ -79,6 +79,7 @@
       <feature id="org.csstudio.applications.logbook.feature"/>
       <feature id="org.csstudio.applications.pvmanager.diag.feature"/>
       <feature id="org.csstudio.email.feature"/>
+      <feature id="org.csstudio.core.trayicon.feature"/>
    </features>
 
    <configurations>
```

Fingers crossed.

**Comment by lcavalli** [comment]
Now it works very well. Thanks.
I'm using Fedora with Gnome 3.24 and a shell extension to move tray icons to top bar.

I'm going to close pull request #2205.

**Comment by willrogers** [comment]
Good!

By the way, where do you work?  I don't see your name on the list of site representatives in https://github.com/ControlSystemStudio/cs-studio/issues/2267.

**Comment by lcavalli** [comment]
@willrogers because I'm not a site representative. My company is developing a new telescope for ESA (the project is still on going and not yet delivered) and the system is based on EPICS and cs-studio. I'm a simple user.

**Comment by berryma4** [comment]
Thank you!

**Pull request merged**
