### PR TITLE
Update versions on opibuilder plugins and features.

### PR DESCRIPTION
**Pull request by willrogers**
Someone needed to do this so I've given it a go.

I have updated opibuilder to 5.0.0.  I don't mind that it's not the same as the CSS version and it is definitely a major update.

I haven't changed rap plugins because I don't understand them.

If a plugin has changed I've updated the major version.  If a plugin hasn't changed I **haven't** updated the version.

I don't mind if people want to do this differently @kasemir @berryma4 @shroffk .

See #1510.

### CODE REVIEW

**Comment by berryma4** [comment]
thank you!

**Comment by shroffk** [comment]
Thanks for updating all the version numbers Will.

In the future do you think it makes sense to manage the version numbers at an entire module level (logbook, alarm, opibuilder) using maven release?

We could then use maven to manage the version numbers, such that with each release build of that module all the sub modules get automatically updated.
http://maven.apache.org/maven-release/maven-release-plugin/examples/prepare-release.html

but we have to agree that all sub modules will have the same version numbers.

**Comment by willrogers** [comment]
Kunal's suggestion would make keeping the version numbers up to date so much easier that I am inclined to agree.

I can't think of a situation where it would be important to have separate versions for different plugins in a module.

**Comment by kasemir** [comment]
Does the maven release mechanism overwrite the version info inside the pom files? Or does this require using variables?

If the maven release mechanism overwrites the underlying pom file versions, I'm all for it.
That way we can usually release the whole module as version 4.1.0, 4.2.0, etc.
But if for some reason one plugin needs to be updated in between, we could manually update just plugin to 4.1.1, 4.1.2, .. until the next whole module update that goes to 4.2.0.

**Comment by berryma4** [comment]
We are using the maven/tycho update versions in org.csstudio.product.  It works nicely, modifying the poms and manifests.  I not sure how to use the maven release plugin, because it doesn't update the manifest.  Maybe we could tie the tycho update versions to a phase in maven release?  Is that possible?

We have discussed versions before, but we should make this an official project for 4.3.x, and call this version change as okay on 4.2.x.

**Comment by shroffk** [comment]
I guess this is the plugin we should use is
https://eclipse.org/tycho/sitedocs/tycho-release/tycho-versions-plugin/plugin-info.html

This plugin should manage the version numbers in both the pom.xml and the manifest files.
I think the tycho version plugin will work as you described Kay, the versions will be updated only once we do a release, and individual plugins and feature versions can be managed manually if need be.

**Comment by berryma4** [comment]
I use this for the org.csstudio.product, examples:
https://github.com/ControlSystemStudio/org.csstudio.product/blob/master/prepare-release.sh
https://github.com/ControlSystemStudio/org.csstudio.product/blob/master/prepare-next-release.sh
(although it doesn't move .product versions up)

**Pull request merged**
