### PR TITLE
Check Box widget auto size issue

### LINKED ISSUE #1943: Check Box widget auto size issue
Hi All,

The check box widget has a Label property. It is expected that when the property auto size is checked, changing the length of the label shall resize the widget automatically.
It is not the case.

To resolve this I propose following changes.

```
diff --git a/applications/opibuilder/opibuilder-plugins/org.csstudio.opibuilder.widgets/src/org/csstudio/opibuilder/widgets/editparts/CheckBoxEditPart.java b/applications/opibuilder/opibuilder-plugins/org.csstudio.opibuilder.widgets/src/org/csstudio/opibuilder/widgets/editparts/CheckBoxEditPart.java
index f79118c..795cd17 100644
--- a/applications/opibuilder/opibuilder-plugins/org.csstudio.opibuilder.widgets/src/org/csstudio/opibuilder/widgets/editparts/CheckBoxEditPart.java
+++ b/applications/opibuilder/opibuilder-plugins/org.csstudio.opibuilder.widgets/src/org/csstudio/opibuilder/widgets/editparts/CheckBoxEditPart.java
@@ -190,7 +190,7 @@
      * @param figure
      */
     private void performAutoSize(IFigure figure) {
-        getWidgetModel().setSize(((CheckBoxFigure)figure).getPreferredSize());
+        getWidgetModel().setSize(((CheckBoxFigure)figure).getAutoSizeDimension());
     }
 
 
diff --git a/applications/opibuilder/opibuilder-plugins/org.csstudio.swt.widgets/src/org/csstudio/swt/widgets/figures/CheckBoxFigure.java b/applications/opibuilder/opibuilder-plugins/org.csstudio.swt.widgets/src/org/csstudio/swt/widgets/figures/CheckBoxFigure.java
index a14789f..cf49d2c 100644
--- a/applications/opibuilder/opibuilder-plugins/org.csstudio.swt.widgets/src/org/csstudio/swt/widgets/figures/CheckBoxFigure.java
+++ b/applications/opibuilder/opibuilder-plugins/org.csstudio.swt.widgets/src/org/csstudio/swt/widgets/figures/CheckBoxFigure.java
@@ -21,6 +21,7 @@
 import org.csstudio.swt.widgets.util.GraphicsUtil;
 import org.csstudio.ui.util.ColorConstants;
 import org.csstudio.ui.util.CustomMediaFactory;
+import org.csstudio.ui.util.Draw2dSingletonUtil;
 import org.eclipse.draw2d.ActionEvent;
 import org.eclipse.draw2d.ActionListener;
 import org.eclipse.draw2d.Cursors;
@@ -68,11 +69,13 @@
 
     private Boolean support3d;
 
-    private Color selectedColor=ColorConstants.darkGray;;
+    private Color selectedColor=ColorConstants.darkGray;
+
+    private BoxFigure boxFigure;
 
     public CheckBoxFigure(final boolean runMode) {
         this.runMode = runMode;
-        final BoxFigure boxFigure = new BoxFigure();
+        boxFigure = new BoxFigure();
         setContents(boxFigure);
         if(!runMode)
             setEventHandler(null);
@@ -292,8 +295,17 @@
         this.totalBits = totalBits;
     }
 
+    public Dimension getAutoSizeDimension() {
+        Dimension d = boxFigure.getAutoSizeDimension();
+        int textWidth = d.width();
+        d.setWidth(textWidth + BOX_SIZE + GAP);
+        return d;
+    }
+
 
     class BoxFigure extends Figure{
+        Dimension textSize;
+
         @Override
         protected void paintClientArea(Graphics graphics) {
             if(support3d == null)
@@ -323,7 +335,7 @@
                 });
             }
             graphics.popState();
-            Dimension textSize = FigureUtilities.getTextExtents(text, graphics.getFont());
+            textSize = FigureUtilities.getTextExtents(text, graphics.getFont());
 
             if (!isEnabled()) {
                 graphics.translate(1, 1);
@@ -337,6 +349,28 @@
             super.paintClientArea(graphics);
 
         }
+
+        @Override
+        public Dimension getPreferredSize(int wHint, int hHint) {
+            return getTextSize();
+
+        }
+
+
+        protected Dimension getTextSize() {
+            if (textSize == null)
+                textSize = calculateTextSize();
+            return textSize;
+        }
+
+        protected Dimension calculateTextSize() {
+            return Draw2dSingletonUtil.getTextUtilities().getTextExtents(text, getFont());
+        }
+
+        protected Dimension getAutoSizeDimension(){
+            return getPreferredSize().getCopy().expand(
+                    getInsets().getWidth(), getInsets().getHeight());
+        }
     }
```

Could anyone verify this?

Regards

### PR DESCRIPTION
**Pull request by rosarp**
Fixed #1943

### CODE REVIEW

**Comment by berryma4** [comment]
```java
Test set: org.csstudio.swt.rtplot.util.UpdateThrottleTest
-------------------------------------------------------------------------------
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.307 sec <<< FAILURE! - in org.csstudio.swt.rtplot.util.UpdateThrottleTest
testUpdateThrottle(org.csstudio.swt.rtplot.util.UpdateThrottleTest)  Time elapsed: 0.296 sec  <<< FAILURE!
java.lang.AssertionError: 
Expected: <1>
     but: was <0>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at org.csstudio.swt.rtplot.util.UpdateThrottleTest.testUpdateThrottle(UpdateThrottleTest.java:52)

```

**Comment by kasemir** [comment]
The test failure seems unrelated to the changes.

That test is timing dependent. It "works for me" right now as well as in recent Hudson builds.
We did increase some other time delay in the same test file 2 months ago, similar scenario.

**Comment by berryma4** [comment]
Last three PRs have this issue, maybe faster/slower computers at TravisCI?

**Comment by kasemir** [comment]
I'll create pull request with larger time delays

**Pull request merged**
