### PR TITLE
BOY Polyline connector fix

### PR DESCRIPTION
**Pull request by css-iter**
The pull request for the issue described in #2187

### CODE REVIEW

**Comment by berryma4** [comment]
Could you please rebase

**Comment by css-iter** [comment]
Just to make sure that I understand correctly (I haven't used the git in all its glory yet :). You want me to rebase this branch on master?

**Comment by berryma4** [comment]
yes, the goal is to remove the commits that are already on mater from your pull request.

**Comment by mvitorovic** [comment]
The branch rebased on master.

**Comment by berryma4** [comment]
I tried to rebase this for you, but you have other commits that master doesn't have, and doesn't not apply to this pull request.  #2197 is this what you were trying to change?

**Comment by kasemir** [comment]
It changes two `.classpath` files from 
```
<classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER">
```
to
```
<classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-1.8"/>
```
Can the .classpath file changes be removed from the pull request?

**Comment by mvitorovic** [comment]
I'll take care of it. I just hope I can find why Eclipse changes that so I will not have to fight with it for each pull request :)

**Comment by mvitorovic** [comment]
This pull request has now been updated with the latest changes. I know it contains a lot of old merges as well, but unfortunately that is from before my time.
It contains fixes that allow the connection between a normal widget and a polyline/polygon widget. The fixes also include the fixed point routing and take care that moving widget also draw the route correctly. There were also issues with the fixed point routing inside the linking containers, which also work correctly for most sane use cases.

**Comment by css-iter** [comment]
CI says build failed, but searching Maven says all builds "SUCCESS", and search for "Failures: [1-9]", and "Errors: [1-9]" returned nothing. The lat lines of the log also don't indicate what could be wrong.
`
travis_time:end:0b8fae95:start=1496305342052467780,finish=1496305342345767467,duration=293299687
travis_fold:end:after_failure.1
travis_fold:start:after_failure.2
travis_time:start:0003ebe1
$ find . -type f -name "*.log" -print0 -exec cat {} \;

travis_time:end:0003ebe1:start=1496305342366019577,finish=1496305342530846049,duration=164826472
travis_fold:end:after_failure.2

Done. Your build exited with 1.
`

**Comment by berryma4** [comment]
```java 
/home/travis/build/ControlSystemStudio/cs-studio/core/utility/utility-plugins/org.csstudio.logging.ui/.classpath:3:1: error: Line contains a tab character.
/home/travis/build/ControlSystemStudio/cs-studio/core/utility/utility-plugins/org.csstudio.logging.ui/.classpath:4:1: error: Line contains a tab character.
/home/travis/build/ControlSystemStudio/cs-studio/core/utility/utility-plugins/org.csstudio.logging.ui/.classpath:5:1: error: Line contains a tab character.
/home/travis/build/ControlSystemStudio/cs-studio/core/utility/utility-plugins/org.csstudio.logging.ui/.classpath:6:1: error: Line contains a tab character.
/home/travis/build/ControlSystemStudio/cs-studio/core/utility/utility-plugins/org.csstudio.logging.ui/.classpath:7:1: error: Line contains a tab character.
/home/travis/build/ControlSystemStudio/cs-studio/core/utility/utility-plugins/org.csstudio.logging.ui/.classpath:8:1: error: Line contains a tab character.
/home/travis/build/ControlSystemStudio/cs-studio/core/utility/utility-plugins/org.csstudio.logging.ui/.classpath:9:1: error: Line contains a tab character.
/home/travis/build/ControlSystemStudio/cs-studio/core/utility/utility-plugins/org.csstudio.logging.ui/.classpath:10:1: error: Line contains a tab character.
```

**Comment by css-iter** [comment]
Thanks, I honestly didn't find it.

**Comment by css-iter** [comment]
I think this is ready for merge now.

**Pull request merged**
