### PR TITLE
4.5 patches

### PR DESCRIPTION
**Pull request by shroffk**
As requesting, creating a pull requests for patches from the 4.3 branch
#2016 #2001
Please delete branch after merging.

### CODE REVIEW

**Comment by shroffk** [comment]
Travis complains about

'''
/home/travis/build/ControlSystemStudio/cs-studio/applications/scan/scan-plugins/org.csstudio.scan.diirt.datasource.info/html/scan-datasource.html:11: error: Trailing whitespaces
/home/travis/build/ControlSystemStudio/cs-studio/applications/scan/scan-plugins/org.csstudio.scan.diirt.datasource.info/html/scan-datasource.html:15: error: Trailing whitespaces
/home/travis/build/ControlSystemStudio/cs-studio/applications/scan/scan-plugins/org.csstudio.scan.diirt.datasource.info/html/scan-datasource.html:18: error: Trailing whitespaces
/home/travis/build/ControlSystemStudio/cs-studio/applications/scan/scan-plugins/org.csstudio.scan.diirt.datasource.info/html/scan-datasource.html:20: error: Trailing whitespaces
/home/travis/build/ControlSystemStudio/cs-studio/applications/scan/scan-plugins/org.csstudio.scan.diirt.datasource.info/html/scan-datasource.html:29: error: Trailing whitespaces
/home/travis/build/ControlSystemStudio/cs-studio/applications/scan/scan-plugins/org.csstudio.scan.diirt.datasource.info/html/scan-datasource.html:34: error: Trailing whitespaces
/home/travis/build/ControlSystemStudio/cs-studio/applications/scan/scan-plugins/org.csstudio.scan.diirt.datasource.info/html/scan-datasource.html:35: error: Trailing whitespaces
/home/travis/build/Contr
'''

none of these files are touched in this pull request? is there something missing here?
Checkstyle checks on the modules affected (logbook and alarm pass without any complains)

**Comment by berryma4** [comment]
Strange that it would complain now, and not for their pull request or merge.

**Comment by berryma4** [comment]
I'm away from a computer, could you add a new pull request for just the whitespace fixes.

**Comment by shroffk** [comment]
Sure...
Although just another observation...this is an html file, do we enforce our stylesheet on .html files too?

**Comment by shroffk** [comment]
In eclipse you need to tell eclipse to check styles on no src files too....this information is currently not part of our eclipse chceckstylesheet but applied by maven check style plugin

**Comment by shroffk** [comment]
The problem with the sytle is resolved but travis just times out

```The job exceeded the maximum time limit for jobs, and has been terminated.```

**Comment by berryma4** [comment]
Strange, past builds took ~30 minutes (50 minutes is the max).
I usually got this in the past, because of p2 repo timeouts taking too long.
Is there a new long test?  slower machines?

**Comment by shroffk** [comment]
Well these is nothing in this pull request which results in any such changes
How is the main master still building?

**Comment by berryma4** [comment]
My guess is the p2 repos are slow, or the machines are slower.

23:42 minutes:seconds (12 days ago)
https://travis-ci.org/ControlSystemStudio/cs-studio/builds/186084915

Exceeds 50 minutes (today):
https://travis-ci.org/ControlSystemStudio/cs-studio/builds/188615508

**Comment by berryma4** [comment]
The network looks about twice as fast on the passing job.
(looking over the reported MB/s for downloading jars)

**Comment by berryma4** [comment]
pace test failure?

**Comment by kasemir** [comment]
I don't understand the output. Did the attempt to actually execute the test fail?
````
An error has occurred. See the log file
/home/travis/build/ControlSystemStudio/cs-studio/applications/display/display-plugins/org.csstudio.display.pace.test/target/work/configuration/1483539342408.log.
...
[INFO] org.csstudio.display.pace.test .................... FAILURE [21.825s]
...
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-surefire-plugin:0.23.1:test (default-test)
on project org.csstudio.display.pace.test:
An unexpected error occured while launching the test runtime (return code 13). See log for details. -> [Help 1]
````
I don't see preceeding compilation errors.

**Comment by shroffk** [comment]
Reverted the stylesheet fixes since they are already addressed by @willrogers

**Comment by berryma4** [comment]
You still have this error:
```
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-surefire-plugin:0.23.1:test (default-test) on project org.csstudio.display.pace.test: An unexpected error occured while launching the test runtime (return code 13). See log for details. -> [Help 1]
[ERROR] 
```

**Comment by kasemir** [comment]
What does that mean, other than some internal error that prevents the tests from starting?
The previous test output
```
.. error has occurred. See the log file...pace.test/target/work/configuration/1483539342408.log.
...
An unexpected error occured while launching the test runtime (return code 13). See log for details. -> [Help 1]
```
suggests that there is a log in the config dir that would explain what's going on. Can you see such a log?

**Comment by berryma4** [comment]
we would need to add ```cat pace.test/target/work/configuration/*.log``` to the .travis.yml file.

**Comment by kasemir** [comment]
Did you capture any useful *.log?

**Comment by shroffk** [comment]
Yes, I will create some pull requests with 
 -  travis.yml update which prints logs on failure
 - maybe each of these patches as separate PR

**Comment by berryma4** [comment]
Ah, ```Bundle was not resolved because of a uses constraint violation.```  Dependency chain issue from your logbook import packages with required plugins change.

**Comment by shroffk** [comment]
This was only the last commit.
The the previous errors are still unexplained (time outs, checkstyles caused on files not assocaited with this PR...)

**Pull request closed without merging**
