### PR TITLE
Closes #2081

### LINKED ISSUE #2081: Many Diirt temporary files
After @claudio-rosati's (very useful) work on diirt, I'm getting a lot of temporary files left behind in `/tmp`.  Could we do better at cleaning up?

https://docs.oracle.com/javase/7/docs/api/java/nio/file/Files.html#createTempDirectory%28java.nio.file.Path,%20java.lang.String,%20java.nio.file.attribute.FileAttribute...%29

diirt-tmp

### PR DESCRIPTION
**Pull request by claudio-rosati**

### CODE REVIEW

**Comment by berryma4** [comment]
Next time please squash all the merge commits.
Thank you!

**Comment by claudio-rosati** [comment]
It is not clear to me if this 'squash' operation is something I have to do on thw web interface of GitHub after the pull request, os something to be done in my forked (or local?) version before the pull request.

**Comment by claudio-rosati** [comment]
[Here](https://github.com/blog/2141-squash-your-commits) is said that should be repository administrators options that should allow squashing when the pull request is performed.

**Comment by claudio-rosati** [comment]
I've spent my last 3 hours to try to understand how to perform squash without success.
Can you please address me on the right way of doing it?

**Comment by berryma4** [comment]
Considering you just want to drop the merge commits, try reading about git rebase.

**Pull request merged**
