### PR TITLE
Update to Eclipse 4.5 Mars #1064, move to 4.2

### PR DESCRIPTION
**Pull request by berryma4**
I have also removed 32-bit builds
#1064

### CODE REVIEW

**Comment by berryma4** [comment]
@shroffk @kasemir this "builds" for me ... any objections?

**Comment by berryma4** [comment]
I also added a target file for @shroffk

**Comment by kasemir** [comment]
If you get "mvn clean verify" to build with this, I'm all for merging.

**Comment by kasemir** [comment]
I get maven errors, for example these in 'core':
````
[ERROR]   The project org.csstudio:utility:[unknown-version] (/home/ky9/git/cs-studio/core/utility/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM: Could not find artifact org.csstudio:core:pom:4.1.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 4, column 11 -> [Help 2]
[ERROR]   
[ERROR]   The project org.csstudio:diirt:[unknown-version] (/home/ky9/git/cs-studio/core/diirt/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM: Could not find artifact org.csstudio:core:pom:4.1.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 3, column 11 -> [Help 2]
[ERROR]   
[ERROR]   The project org.csstudio:base:[unknown-version] (/home/ky9/git/cs-studio/core/base/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM: Could not find artifact org.csstudio:core:pom:4.1.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 3, column 11 -> [Help 2]
[ERROR]   
[ERROR]   The project org.csstudio:platform:[unknown-version] (/home/ky9/git/cs-studio/core/platform/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM: Could not find artifact org.csstudio:core:pom:4.1.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 4, column 11 -> [Help 2]
[ERROR]   
[ERROR]   The project org.csstudio:ui:[unknown-version] (/home/ky9/git/cs-studio/core/ui/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM: Could not find artifact org.csstudio:core:pom:4.1.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 4, column 11 -> [Help 2]
[ERROR]   
[ERROR]   The project org.csstudio:unorganized:[unknown-version] (/home/ky9/git/cs-studio/core/unorganized/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM: Could not find artifact org.csstudio:core:pom:4.1.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 4, column 11 -> [Help 2]
[ERROR]   
[ERROR]   The project org.csstudio:core-p2repo:[unknown-version] (/home/ky9/git/cs-studio/core/p2repo/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM: Could not find artifact org.csstudio:core:pom:4.1.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 3, column 11 -> [Help 2]
[ERROR] 
````

Just looking at the first one, it makes some sense to me.
`cs-studio/core/utility/pom.xml` contains
````
 <parent>
    <groupId>org.csstudio</groupId>
    <artifactId>core</artifactId>
    <version>4.1.0-SNAPSHOT</version>
  </parent>
````
The actual parent file, i.e. `cs-studio/core/pom.xml`, was just updated to 
````
  <groupId>org.csstudio</groupId>
  <artifactId>core</artifactId>
  <version>4.2.0-SNAPSHOT</version>
````

So there's a mismatch of parent version 4.2.0 vs. 4.1.0.

**Comment by berryma4** [comment]
I just noticed the error this morning ... at the moment I'm questioning why
it works on my box.

**Comment by kasemir** [comment]
I've started to update all the `cs-studio/core/utility/*/pom.xml` to have a 4.2.0 `<parent>`, which would be correct, right?

**Comment by berryma4** [comment]
I'm already updating it too ... I'll push to the same branch

**Comment by berryma4** [comment]
ugh ... still incomplete ... I need to do all the way down the tree

**Comment by berryma4** [comment]
I would like to know why this works on my box ... it must be resolving an install?

**Comment by berryma4** [comment]
Our version-ing in the pom files is not very uniform ....

**Comment by kasemir** [comment]
Compiles now for me as well, thanks!

**Comment by kasemir** [comment]
Checking again, it build, but I still get luna plugins.
One reason seems cs-studio-thirdparty/pom.xml, which still points to css 4.2, luna, eclipse/updates/4.4

**Comment by berryma4** [comment]
Ah, I already made a 4.2.x branch for third party and Maven osgi bundles

**Comment by kasemir** [comment]
Since cs-studio/master has the Luna settings, I'm for merging the 4.2 branches of 3rd party and mvn usage bundles into their respective master.

**Comment by berryma4** [comment]
thank you!

**Comment by nickbattam** [comment]
I tried to build the DLS product from pvmanager though to our CSS product using the 4.2 / Mars build.

The build fails as there are still references to 4.1.0-SNAPSHOT in the top-level pom files:
- applications/p2repo/pom.xml
- core/p2repo/pom.xml

`[ERROR] The build could not read 1 project -> [Help 1]
`[ERROR]   
`[ERROR]   The project org.csstudio:core-p2repo:[unknown-version] (/scratch/CSS/css-source/cs-studio/core/p2repo/pom.xml) has 1 error
`[ERROR]     Non-resolvable parent POM: Could not find artifact org.csstudio:core:pom:4.1.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 3, column 11 -> [Help 2]

`[ERROR] The build could not read 1 project -> [Help 1]
`[ERROR]   
`[ERROR]   The project org.csstudio:applications-p2repo:[unknown-version] (/scratch/CSS/css-source/cs-studio/applications/p2repo/pom.xml) has 1 error
`[ERROR]     Non-resolvable parent POM: Could not find artifact org.csstudio:applications:pom:4.1.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 3, column 11 -> [Help 2]

**Comment by berryma4** [comment]
Are you sure you have pulled the latest changes?  I believe I fixed this in
the pull requests following this one.

**Comment by nickbattam** [comment]
Yes, I am building from master (5113f).

I'm running maven from the top-level applications/ and core/ folders, rather than building the features separately. It's possible the content of the pom at this level isn't used by the cloudbees build.

**Comment by kasemir** [comment]
I see that error as well.
The problem is in cs-studio/core/p2repo/pom.xml still referring to 
````
<parent>
    <version>4.1.0-SNAPSHOT</version>
````
instead of using 4.2.0-SNAPSHOT

**Comment by kasemir** [comment]
yes, changing the 4.1 into a 4.2 in cs-studio/core/p2repo/pom.xml will allow the core build to succeed.
Ggood example for a change we I'd love to just edit the '1' into a '2' in the github web editor instead of branch, commit, pull request.

**Pull request merged**
