### PR TITLE
Attempt to fix tests that use JAXB after JDK-11 changes.

### PR DESCRIPTION
**Pull request by willrogers**
These copy the changes in the rest of cs-studio, but the test still
fails to find JAXB-API.

Don't merge! This doesn't fix the problem for me.

@berryma4 @shroffk

### CODE REVIEW

**Comment by georgweiss** [comment]
I see the same here at ESS.

**Comment by willrogers** [comment]
I don't know why this doesn't work, @berryma4 is the most likely to understand. Is the test classloader different to the runtime classloader?

**Comment by georgweiss** [comment]
What about considering a different XML parsing strategy? Like XMLBeans or DOM.

**Comment by kasemir** [comment]
DOM's what I tend to use...

**Comment by berryma4** [comment]
Sorry, I was on vacation for a bit ...
I'm going to assume the issue is that you need to pass the JAXBContextFactory parameter through mvn:
```
-Djavax.xml.bind.JAXBContextFactory=com.sun.xml.bind.v2.ContextFactory
```

**Comment by georgweiss** [comment]
I'm sorry, but -Djavax.xml.bind.JAXBContextFactory=com.sun.xml.bind.v2.ContextFactory does not make a difference for the build on my box. Still fails in the same manner.

**Comment by willrogers** [comment]
It looks like it should be `javax.xml.bind.context.factory`, but that still doesn't work for me in Tycho.

**Comment by berryma4** [comment]
Your right, it seems the property is not read reliably in maven. I added a jaxb.properties file, which might be better anyway.

**Comment by willrogers** [comment]
I also needed a `jaxb.index` file. After that the test passed.

I'm not sure how you pushed to this branch.

**Comment by berryma4** [comment]
I was surprised I could push too!

**Comment by berryma4** [comment]
It might be a good idea to not use the environment variable, and drop the property files in everywhere needed instead.

**Comment by berryma4** [comment]
I wonder why I didn't need the ```jaxb.index``` file to pass the test? It's more correct to have it though.

**Comment by willrogers** [comment]
I also had to replace some tabs with spaces, but it builds for me now. I'm happy to merge.

**Comment by berryma4** [comment]
#2589

**Comment by georgweiss** [comment]
Build now fails at later point:

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.004 s - in org.csstudio.swt.rtplot.TraceAnalyzerTest
testFindSample(org.csstudio.swt.rtplot.TraceAnalyzerTest)  Time elapsed: 0.003 s
Running org.csstudio.swt.rtplot.LinearTicksTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.003 s - in org.csstudio.swt.rtplot.LinearTicksTest
testNiceDistance(org.csstudio.swt.rtplot.LinearTicksTest)  Time elapsed: 0.002 s
testPrecision(org.csstudio.swt.rtplot.LinearTicksTest)  Time elapsed: 0 s

Results:

Failures: 
  UpdateThrottleTest.testUpdateThrottle:63 
Expected: <2>
     but: was <3>

Tests run: 13, Failures: 1, Errors: 0, Skipped: 0

**Comment by kasemir** [comment]
`UpdateThrottleTest` could be sensitive to timing and CPU load.
Does it fail each time?

**Comment by willrogers** [comment]
It's passing for me.

**Comment by kasemir** [comment]
We have several tests which prove that Java is not a real-time system. They do occasionally fail.

**Comment by georgweiss** [comment]
One might argue that the test in question should be reworked.

**Comment by kasemir** [comment]
Yes, ideally by somebody who sees it fail right now, so you can adjust the timing.

**Comment by kasemir** [comment]
For that specific one, we've tried several times when we hit timing constraints:
```
git log UpdateThrottleTest.java
commit 975513d5051fb958ef7e9cca1fd6594a95e931dc
Author: Claudio Rosati <Claudio.Rosati@esss.se>
Date:   Thu Jul 6 15:44:13 2017 +0200
    o.c.swt.rtplot.test: update tests
commit 73499d9b94333aca82bfecdc5034de4a9d94706a
Author: kasemir <kay.kasemir@gmail.com>
Date:   Mon Nov 7 16:27:31 2016 -0500
    o.c.swt.rtplot.test: Increase times in time-related test
    Should help avoid test failures as seen in #1947
commit f3b21f12dc45be3654c43da4f52d35e5d8b00e45
Author: kasemir <kasemirk@ornl.gov>
Date:   Thu Sep 15 10:14:40 2016 -0400
    swt.rtplot: Increase time delay to allow test to pass
    #1898
```

**Comment by kasemir** [comment]
It's easy to throw stones at this type of test, but I'm not sure how to improve them.
This is about testing time-related logic, like a throttle which suppresses some events but then issues an event, ideally within some time.
So we expect an event within say half a second.
Just to make sure we wait 2 seconds.
Most of the time this works out, but especially on cloud setups (travis, ..) it often takes a lot longer.
What to do? Wait 60 seconds? That defeats the test.
Skip the test because timing can't be dependable?
For now I prefer to have the test and just ignore occasional failures, because most of the time it works and might help to catch a real problem if it suddenly fails every time.

**Comment by georgweiss** [comment]
What about rewriting the test to wait for 2 seconds, and exponentially increase the wait time up to a limit where we consider the test useless.

**Comment by kasemir** [comment]
Well, that's a little nicer than this specific test, but doesn't solve the failures.
Assume we expect something to happen in 0.5 seconds.
Then this is clearly a waste of time because you always delay for 5 seconds:
```
TimeUnits.SECONDS.sleep(5);
assert(.. that it happened);
```

Instead of inventing a new machinery that sleeps 1 second, then 2, then 4, .. newer tests tend to use for example a `CountDownLatch` or a `BlockingQueue` so you can wait for the result like this:
```
assert(  block.poll(5, TimeUnit.SECONDS) == expected_result );
```

That way we don't waste time waiting; you move on as soon as you have the result, or time out.

The big issue, however, is that these tests sometimes do time out when run on build servers.
Take https://github.com/shroffk/phoebus/blob/master/services/alarm-server/src/test/java/org/phoebus/applications/alarm/server/AutomatedActionTest.java#L217:
It usually runs fine, reacting within 1 ms of the expected time:
```
Action performed after 1001 ms (expected: 1000 ms)
```

But I just got a travis email that it timed out after waiting for 5 seconds.
You'd think that 5 seconds is ample time for what usually happens in 1ms.

**Pull request merged**
