### PR TITLE
The issue with connector to polyline is now solved.

### PR DESCRIPTION
**Pull request by berryma4**
Do not merge!!

### CODE REVIEW

**Comment by shroffk** [comment]
I am solving these issues on the main PR

**Comment by berryma4** [comment]
Really?  this was in reference to #2188

**Comment by shroffk** [comment]
Sorry, my bad, I was referring to the checkstyle errors and invalid inherited doc's

**Comment by berryma4** [comment]
I don't plan on merging it, I'm trying to help PR #2188 understand rebase

**Comment by kasemir** [comment]
How do you do the squash/rebase? From the git command line, or in Eclipse via Team History, context menu, Modify/Squash?
How does that work when the individual commits have already been pushed, and somebody else has that branch on their computer with separate commits?

**Comment by berryma4** [comment]
Yes, you aren't supposed to rebase a public branch (since you are rewriting history).  I did this as an example to PR #2188, in which their branch has "extra" commits they should clean up.

**Pull request closed without merging**
