### PR TITLE
Suggest changing perspective on opening OPIEditor.

### PR DESCRIPTION
**Pull request by willrogers**
Don't merge this yet.

Tie to a preference so that choice can be remembered.  Set up listeners
on workbench components to ensure this is active for each new part.

See #1568.

Method suggested by Dawn devs: set up PartListeners that trigger on opening a new part.  In practice, this requires multiple listeners in order to ensure that the hook is active in all parts of the workbench.

Review @gerring @kasemir .

### CODE REVIEW

**Comment by kasemir** [comment]
How is that functionally different from adding similar checkEditorPerspective() code to the OPIEditor's init() routine? In either case, as an OPI Editor is opened, it checks the perspective and prompts for a change.  Adding it directly to the OPIEditor's init() is less code than adding a listener to every part in every window.

**Comment by willrogers** [comment]
There's one difference:  this way *doesn't* trigger on CSS startup (not sure why, other than the `earlyStartup()` method says it is called after workbench initialisation).

There are cases that OPI editors will be open on shutdown - in particular, if you change perspective editors remain open in the editor stack.  Then when you restart you'll get prompted to change perspective, which might confuse people.

Ideally I'd like this to happen only when someone has actively chosen to edit an OPI, because then it should make sense.  That is, as long as the user understands perspectives, which I think is essential when using eclipse.  And it also requires a better message than I have so far.

**Comment by kasemir** [comment]
Got it. The doesn't-trigger-on-CSS-startup behavior is good.

The only-when-someone-has-actively-chosen-to-edit-an-OPI question is hard.
For the debugger, somebody invokes a "Run in debugger" action.
The equivalent for us would be the navigator action that opens an editor, but I'm not sure if you can hook into that.

**Comment by willrogers** [comment]
I think this commit does achieve that.  There are three cases I can think of:

* File | New | OPI ...
* Right-click in navigator | Open With | OPI Editor
* Right-click on runtime OPI | Edit OPI

These are all caught and are all deliberate actions.  I can't think of another way to open OPIEditor other than CSS startup, and we're skipping that now.

**Comment by kasemir** [comment]
Right.

I'm OK with merging this.

There's no preference to disable it, but worst case you get the dialog once, check "don't ask again" and you're fine. Plus this only applies to people who edit, not beam line users who only execute existing displays.

**Comment by willrogers** [comment]
Hold on before merging, I'll improve the messages.

@berryma4 @shroffk any comments on this feature?

I think a site could set the default preference to "Never", then no users at that site would see the dialog unless they changed the setting themselves.

**Comment by willrogers** [comment]
The latest commit moves all state into the constructor.  This could be turned into an abstract class for any plugin that wanted to use this behaviour to extend.

**Comment by willrogers** [comment]
We've built and tested this locally, and I'm happy for it to be merged @berryma4 .

**Comment by berryma4** [comment]
Thank you!

**Pull request merged**
