### PR TITLE
o.c.graphene.opiwidgets: update reference to org.epics

### PR DESCRIPTION
**Pull request by willrogers**
This reference to `org.epics` was breaking the build.

### CODE REVIEW

**Comment by berryma4** [comment]
@shroffk might care about pretune.  I believe the utilities feature I remove two days ago was the only feature that included graphene.opiwidgets.  We should probably make a new feature for it.

**Comment by berryma4** [comment]
#1470

**Comment by shroffk** [comment]
I will create the new features today

**Comment by berryma4** [comment]
Done, #1476

**Pull request merged**
