### PR TITLE
Jca 2361

### LINKED ISSUE #2361: Update vtype.pv for JCA 2.4, Unable to build cs-studio
Hello,

I hope you all started the new year well. After coming back from my Italian vacation I have the problem of not being able to build cs-studio.

I have 2 pipelines: the _css-ce_ one builds all the projects (`maven-osgi-bundles`, `cs-studio-thirdparty`, `diirt`, `cs-studio`, `org.csstudio.display.builder`, `org.csstudio.product`, and `org.csstudio.ess.product`) against the community master branch, and the _ess-css-development_ one using the ESS forked repositories.

Only when new features/fixes are merged into the community repositories **and** the _css-ce_ pipeline is successful, I synchronize the forked repositories with the community ones.

Now, the _css-cs_ pipeline fails building the `cs-studio` project:

```
...
00:16:58.679 [INFO] Compiling 78 source files to /home/jenkins/workspace/CS-Studio-CE/cs-studio/core/base/base-plugins/org.csstudio.vtype.pv/target/classes
00:16:59.650 [INFO] ------------------------------------------------------------------------
00:16:59.650 [INFO] Reactor Summary:
00:16:59.650 [INFO] 
00:16:59.650 [INFO] core .............................................. SUCCESS [0.567s]
00:16:59.650 [INFO] platform .......................................... SUCCESS [0.082s]
00:16:59.650 [INFO] platform-plugins .................................. SUCCESS [0.003s]
00:16:59.650 [INFO] org.csstudio.jre6.fragment ........................ SUCCESS [7.970s]
00:16:59.650 [INFO] utility ........................................... SUCCESS [0.005s]
00:16:59.650 [INFO] utility-plugins ................................... SUCCESS [0.004s]
00:16:59.650 [INFO] org.csstudio.data ................................. SUCCESS [1.359s]
00:16:59.650 [INFO] org.csstudio.data.test ............................ SUCCESS [8.268s]
00:16:59.650 [INFO] org.csstudio.java ................................. SUCCESS [0.363s]
00:16:59.651 [INFO] org.csstudio.logging .............................. SUCCESS [0.407s]
00:16:59.651 [INFO] org.csstudio.logging.test ......................... SUCCESS [6.414s]
00:16:59.651 [INFO] org.csstudio.logging.ui ........................... SUCCESS [0.600s]
00:16:59.651 [INFO] org.csstudio.openfile ............................. SUCCESS [0.191s]
00:16:59.651 [INFO] org.csstudio.rap.core ............................. SUCCESS [0.584s]
00:16:59.651 [INFO] diirt ............................................. SUCCESS [0.005s]
00:16:59.651 [INFO] diirt-plugins ..................................... SUCCESS [0.003s]
00:16:59.651 [INFO] org.csstudio.diirt.util.core.preferences .......... SUCCESS [0.279s]
00:16:59.651 [INFO] base .............................................. SUCCESS [0.002s]
00:16:59.651 [INFO] base-plugins ...................................... SUCCESS [0.001s]
00:16:59.651 [INFO] org.csstudio.vtype.pv ............................. FAILURE [0.856s]
00:16:59.651 [INFO] org.csstudio.startup .............................. SKIPPED
00:16:59.651 [INFO] org.csstudio.security ............................. SKIPPED
00:16:59.651 [INFO] org.csstudio.workspace ............................ SKIPPED
...
00:16:59.653 [INFO] ------------------------------------------------------------------------
00:16:59.653 [INFO] BUILD FAILURE
00:16:59.653 [INFO] ------------------------------------------------------------------------
00:16:59.653 [INFO] Total time: 5:40.137s
00:16:59.653 [INFO] Finished at: Mon Jan 08 11:07:56 CET 2018
00:17:02.227 [INFO] Final Memory: 470M/1572M
00:17:02.228 [INFO] ------------------------------------------------------------------------
00:17:02.228 [ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:1.0.0:compile (default-compile) on project org.csstudio.vtype.pv: Compilation failure: Compilation failure:
00:17:02.228 [ERROR] /home/jenkins/workspace/CS-Studio-CE/cs-studio/core/base/base-plugins/org.csstudio.vtype.pv/src/org/csstudio/vtype/pv/jca/JCA_Preferences.java:[23]
00:17:02.228 [ERROR] import gov.aps.jca.jni.JNITargetArch;
00:17:02.228 [ERROR] ^^^^^^^^^^^^^^^
00:17:02.228 [ERROR] The import gov.aps.jca.jni cannot be resolved
00:17:02.228 [ERROR] /home/jenkins/workspace/CS-Studio-CE/cs-studio/core/base/base-plugins/org.csstudio.vtype.pv/src/org/csstudio/vtype/pv/jca/JCA_Preferences.java:[145]
00:17:02.228 [ERROR] final String jni_target = JNITargetArch.getTargetArch();
00:17:02.228 [ERROR] ^^^^^^^^^^^^^
00:17:02.228 [ERROR] JNITargetArch cannot be resolved
00:17:02.228 [ERROR] 2 problems (2 errors)
...
```

Any idea? Something dramatic changed since Dec. 15th?

### PR DESCRIPTION
**Pull request by kasemir**
Update vtype.pv to compile with JCA 2.4.

Fixes #2361

### CODE REVIEW

**Comment by kasemir** [comment]
@berryma4 Eric, I need this merged into master so I can work on the other tickets.

**Comment by berryma4** [comment]
Don't we need to add jca 2.4.1 to maven-osgi-bundles first?

**Comment by kasemir** [comment]
In theory, maybe, so feel free to update maven-osgi-bundles first.

In practice, no: Diirt fetches 2.4.1, so those who use the locally compiled diirt from master are OK.
And now that vtype.pv asks for 2.4.1 in its manifest, maven fetches that from wherever.

**Comment by berryma4** [comment]
I've got a pull request which should help it pass:
https://github.com/ControlSystemStudio/maven-osgi-bundles/pull/55

**Comment by kasemir** [comment]
Thanks. Once that's merged, need to re-trigger this build.

**Comment by berryma4** [comment]
I've re-triggered the builds.

**Pull request merged**
