### PR TITLE
Opi validation updates

### PR DESCRIPTION
**Pull request by jbobnar**
Added the opivalidation plugin to the opibuilder feature. Is that OK? Otherwise I need to add an additional feature, containing just this plugin.

Created an application and product configuration to run the validation in a headless mode from command line.

Fixed a few bugs.

### CODE REVIEW

**Comment by berryma4** [comment]
@kasemir @shroffk do we want a new feature for this?  I want this, but does everyone?

**Comment by shroffk** [comment]
Do you know the update site from which the org.eclipse.wst.validation dependency can be resolved? I think the target file might need to be updated to include this dependency.

**Comment by kasemir** [comment]
It'd be nice for the target to be somewhat stable. Maybe change no more than once a month? Eclipse 4.5 Mars is to be released June 24. We should adopt that soon afterwards on 'master', which would also require a new target file.

**Comment by jbobnar** [comment]
@shroffk wst.validation It's part of the eclipse update site.

The current opibuilder feature doesn't look like a proper feature, but more a collection of plugins that are related to opibuilder: adlParser, adl2boy and converter are probably also not needed at every installation.

I'd recommend to remove those plugins from the feature, which are not in the opibuilder-plugins and put them into another feature. The opi builder feature should then be configured to depend on that other feature. If a certain plugin is only used by opibuilder (and there is little or no chance that it will be used somewhere else) it should become a part of this repository.
The problem with the current setup is that if there was another feature that provides the same plugin, you will only be able to install both features in CSS if they both provide the exact same version of the shared plugin.

**Comment by kasemir** [comment]
Which Eclipse update site? Kunal may be correct that it's not in our current cs-studio/target-files/target-dev.target that points to http://download.eclipse.org/eclipse/updates/4.4/R-4.4.2-201502041700.

The current opibuilder feature is certainly a collection of things that not everybody needs, but at the same time adlParser, adl2boy, EDM converter don't cause any visible harm to end users. They hardly add new menu entries, they don't affect the runtime at all. Similarly, I'd be OK with adding the validator. What might be useful is a split into an opiruntime feature (just the runtime) and an opieditor feature (editor, adl2boy, EDM converter, validation, ..).

**Comment by shroffk** [comment]
@jbobnar 
1. I agree with the feature re-organization you mentioned. adlPraser, adl2boy and converter etc should be moved to a different feature but they should still be part of the opibuilder module since they are closely dependent on opibuilder.

2. For the validator I am fine with it being in the main opibuilder feature, so long and the default def file is completely commented out.

3. @kasemir just the runtime could be very interesting.

**Comment by jbobnar** [comment]
@kasemir @shroffk 

Sorry, it's the eclipse releases site, not the update site: http://download.eclipse.org/releases/luna/

**Comment by berryma4** [comment]
@kasemir @shroffk @jbobnar at this point, does this go on 4.1.0 or 4.2.0.  @utzeln do you need this on 4.1.0?

**Comment by berryma4** [comment]
I do like the idea of a opiruntime feature (just the runtime) and an opieditor feature, but this will have to happen in 4.2.x.  I'm merging this to 4.1.x.

**Pull request merged**
