### PR TITLE
#2439 cleanup style sheet violations

### PR DESCRIPTION
**Pull request by shroffk**
#2439 
@berryma4 you could use this PR to test the checkstyle check

### CODE REVIEW

**Comment by berryma4** [comment]
Travis-ci is migrating all of their org account to com account. We seem to be in a org/com limbo at the moment. I have emailed them. At the same time, Github has switched to "Github Apps", which the new Travis-ci "com" account will link. When everything is working, we should see the Travis-ci checks information in the new "Checks" tab in the pull request.

**Comment by shroffk** [comment]
Thanks for following up on this @berryma4

**Comment by berryma4** [comment]
@shroffk could you push another commit to force a trigger.

**Comment by berryma4** [comment]
All repos have been moved to the new .com, and travis has fixed what didn't migrate correctly.

**Pull request merged**
