### PR TITLE
Continued work on Issue 818

### PR DESCRIPTION
**Pull request by shroffk**

### CODE REVIEW

**Comment by kasemir** [comment]
Can we merge this?
Next, I can submit a pull request for a similar core.unorganized.feature.

**Comment by shroffk** [comment]
I can give you access to my repo and you could add your commits to this pull request

**Comment by kasemir** [comment]
Yes: You have the utility and ui features that I need, so let me add the unorganized feature.

**Comment by shroffk** [comment]
Actually you already have all privileges on my repo.
if you add your commits to the "new" branch (sorry for the awful name) they should become part of this pull request.

**Comment by shroffk** [comment]
Had not pushed the changes that populated the utility.feature

**Comment by berryma4** [comment]
#818

**Comment by kasemir** [comment]
I get this error:

[ERROR]   Missing requirement: org.csstudio.ui.feature.feature.group 4.1.0 requires 'org.csstudio.ui.menu.app 0.0.0' but it could not be found

**Comment by kasemir** [comment]
org.csstudio.ui.menu.app is in applications, so there should be no feature in core that lists it..

**Comment by kasemir** [comment]
core/ui/ui-features/org.csstudio.ui.feature/feature.xml seems way to long.
Should only list 
org.csstudio.ui.help
org.csstudio.ui.menu
org.csstudio.ui.preferences
org.csstudio.ui.util

**Comment by kasemir** [comment]
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-p2-repository-plugin:0.22.0:assemble-repository (default-assemble-repository) on project utility-repository: No content specified for p2 repository -> [Help 1]

I'll add something to utility-repository/category.xml

**Comment by kasemir** [comment]
Eric moved o.c.java, so now there's a merge conflict

**Comment by kasemir** [comment]
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-p2-repository-plugin:0.22.0:assemble-repository (default-assemble-repository) on project ui-repository: No content specified for p2 repository -> [Help 1]

I'll add the core/ui feature to the core/ui-repository

**Comment by kasemir** [comment]
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-packaging-plugin:0.22.0:validate-version (default-validate-version) on project org.csstudio.ui.feature: OSGi version 4.1.0 must have .qualifier qualifier for SNAPSHOT builds -> [Help 1]

Adding .qualifier

**Comment by berryma4** [comment]
wait one second, ... I'm going to merge this to master and resolve conflicts

**Comment by kasemir** [comment]
I'm not sure this is done, there's been little things missing in the ui, utility, unorganized features or repos

**Comment by kasemir** [comment]
Alright, 'core' builds again.
Not sure if the core/*/*/repos are good enough for applications, but you're right, this might be a good time to merge to master and then address the next errors against master.

**Pull request merged**
