### PR TITLE
Issue #1573 Get list of possible enum values

### PR DESCRIPTION
**Pull request by laurent-PHILIPPE**
Link to issue #1573.

Sorry for the delay in pull creation.

### CODE REVIEW

**Comment by willrogers** [comment]
Hi,

I'm not sure where it's documented (@berryma4, is it somewhere?) but we have a convention to use four spaces for indentation and no whitespace at the end of lines.

You can make Eclipse show you:
spaces-and-tabs

I've put a pull request to your branch to fix it.  Don't be put off contributing we're all friendly!

Cheers,
Will

**Comment by laurent-PHILIPPE** [comment]
Ok, thanks for the correction.
Is someone proposing an eclipse code formatter to assure a correct formatting?

**Comment by willrogers** [comment]
Yes, this is a good idea if it doesn't exist already.

**Comment by kasemir** [comment]
I use https://github.com/ControlSystemStudio/org.csstudio.sns/blob/master/plugins/org.csstudio.sns.product/code_format.xml to format the code. That gets you the basic space-instead-of-tabs and puts the braces in the correct location.
In addition, I enable Editor "Save Actions" to trim trailing whitespace, organize imports.

**Comment by berryma4** [comment]
Funny, we have the checkstyle and not the format.xml.  Maybe we should move Kay's to cs-studio/build/?

**Comment by berryma4** [comment]
And, thank you @willrogers

**Comment by kasemir** [comment]
For what it's worth, regarding the List to array conversion, there are two useful idioms when converting a list to an array.

1) Let the `toArray()` allocate the memory
```
(String[]) labels.toArray(); 
```
2) You allocate the array with the proper size, `toArray()` only populates it
```
labels.toArray(new String[labels.size()]);
```
in which case the return type already has the correct type.

In Eclipse, if you just type 'toarray' and use completion, you get a template for the second case, which is generally recommended.

The committed code uses
```
labels.toArray(new String[]{}); 
```
which allocates an empty array, passes that to `toArray()` which then needs to allocate another array for the correct `size()`.

No, this extra allocation for naught doesn't matter in the big picture. Just nitpicking.

**Comment by berryma4** [comment]
@kasemir or?
labels.stream().toArray(String[]::new);

**Pull request merged**
