### PR TITLE
2147 pixel conversions 44

### PR DESCRIPTION
**Pull request by willrogers**
See #2147 ported to 4.4.

### CODE REVIEW

**Comment by willrogers** [comment]
I don't know why this didn't trigger a Travis build, but it would be helpful to have this and https://github.com/ControlSystemStudio/cs-studio/pull/2152 merged asap...

**Comment by berryma4** [comment]
Well, this is odd.  Is the 4.4.x branch yml file not parsing correctly?

**Comment by willrogers** [comment]
I bet it was another Travis glitch, because https://github.com/ControlSystemStudio/cs-studio/pull/2151 was opened on the same day but against master.

**Comment by berryma4** [comment]
It seems the easiest way to fix, is to close/reopen the PR.

**Comment by berryma4** [comment]
Should be all set, I'll merge after the tests.
Thank you!

**Pull request merged**
