### PR TITLE
Issue 1088

### PR DESCRIPTION
**Pull request by shroffk**
@berryma4 @kasemir 
Changes were made to RTPlot to support a legend (very basic) which can be shown/hidden

Changes to the databrowser
Model updated to have a field representing the legend font, XMLPersistence saves/loads the legend info from the model
Misc tab provide UI to edit legend font

### CODE REVIEW

**Comment by shroffk** [comment]
@kasemir could you check the use of the SWTMediaPool

**Comment by berryma4** [comment]
#1088

**Comment by kasemir** [comment]
I'll change the whole legend implementation from Composite/Labels/GridLayout into an RTPlot PlotPart that's drawn in background thread.
Kunal, I think I can already write to your repo, so I'll just add commits to this branch & pull request over the next couple days.

**Comment by kasemir** [comment]
Finally got around to fetch the source code. I keep getting
```
java.lang.NullPointerException
	at org.csstudio.swt.rtplot.internal.LegendHandler$1.changedTraces(LegendHandler.java:52)
	at org.csstudio.swt.rtplot.internal.Plot.fireTracesChange(Plot.java:1132)
```
where the code in question is `Display.getCurrent()` being null.

--> Another reason for implementing the legend such that it's drawn in the background as a plot part, so I'll start working on that.

**Comment by kasemir** [comment]
I've changed the legend implementation from Composite/Label to background-drawn within the plot.

You had added both the Toolbar and the Legend visibility to the *.plt model, so they're saved in the config file, changes trigger the 'dirty' indication of the editor. Good.

Since the toolbar visibility wasn't always saved in the *.plt file, the opiwidget had a toolbar property. In hindsight, would have been better to leave that to the *.plt file, but OK, so now the *.plt file has the toolbar property, but the opiwidget has one as well.

For the legend, I think it's best to leave that only in the *.plt file, where luckily it is from the start. So the opiwidget just shows/hides legend as per the *.plt file. Can be changed at runtime, but the opiwidget otherwise doesn't have its own show_legend property.

**Comment by kasemir** [comment]
OK, let me put the opiwidget option to show/hide legend, overriding that setting from the *.plt model, back in.

**Comment by shroffk** [comment]
Sorry about the NPE.

**Comment by kasemir** [comment]
The opiwidget property to show/hide legend is back.
From my side, this is now good, i.e. it's what you had, with legend drawn in plot's thread.

Nice would be a legend that groups by axes, with border that matches axis color.
I don't think I'll get to that right now, and it doesn't affect the properties/config files, so we can leave that for a little later. I do think it's necessary, though, since otherwise the legend (with trace names on the axes turned off) leaves you wondering what's on which axis.

**Comment by berryma4** [comment]
Are we done?

**Comment by kasemir** [comment]
Yes, for now. I'll improve the legend later.

**Pull request merged**
