### PR TITLE
2466 waveform view

### PR DESCRIPTION
**Pull request by willrogers**
This is a number of tweaks to fix and improve the behaviour introduced in #2466.

### CODE REVIEW

**Comment by kasemir** [comment]
I'm not 100% sure about this:
```
final int idx = new TimeDataSearch().findSampleGreaterOrEqual(samples, sliderTime);
sample = samples.get(idx - 1);
```
The located sample index could be 0 (valid, first sample).
But `idx-1` would then result in an error.
For databrowser3, I was that happen when adding two waveforms and then quickly trying to operate the waveform view, so I used `samples.get(idx);` without the `-1`.

**Comment by willrogers** [comment]
Let me think...

**Comment by willrogers** [comment]
OK, I know what I was thinking but in practice yours works better.

**Comment by willrogers** [comment]
I think this one is ready to merge.

**Pull request merged**
