### PR TITLE
#2530: move to tycho 1.4; move efxclipe to 3.5.0

### PR DESCRIPTION
**Pull request by berryma4**
Hoping this speeds up the build:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=544345

### CODE REVIEW

**Comment by berryma4** [comment]
https://bugs.eclipse.org/bugs/show_bug.cgi?id=536928

**Comment by berryma4** [comment]
The org.w3c.dom.* errors seem to be more difficult to fix in other plugins.

**Comment by berryma4** [comment]
https://bugs.eclipse.org/bugs/show_bug.cgi?id=542896
This explains the issue, switching to 4.11 to get the fix.

**Comment by berryma4** [comment]
Funny, this fixed it for me locally. Leave it to Eclipse Tycho to have different results everywhere.

**Comment by willrogers** [comment]
I get the same failure on rdbtable locally.

**Comment by willrogers** [comment]
@shroffk @kasemir any ideas on these errors, given that you looked at similar ones in https://github.com/shroffk/phoebus/issues/80?

**Comment by shroffk** [comment]
I have pulled all the master branches and am building it all now.

**Comment by shroffk** [comment]
I can't reproduce the error, my local build succeeded. 
I built the cs-studio/applications off the master branch (basically the code you merged)

**Comment by berryma4** [comment]
I think you need to merge master back to this and resolve merge conflicts.

**Comment by willrogers** [comment]
@shroffk it's this `issue_2530_EB` branch that's failing.

**Comment by shroffk** [comment]
ok...I am pulling the branch and rebuilding 

ITD has determined that eclipse.launcher is malware so my builds are failing for a whole different set of reasons.

**Comment by shroffk** [comment]
This is insanely infuriating...
Using the solutions listed here:
https://stackoverflow.com/questions/51094274/eclipse-cant-find-xml-related-classes-after-switching-build-path-to-jdk-10/53824670#53824670

I updated the .classpath as follows
```
<?xml version="1.0" encoding="UTF-8"?>
<classpath>
  <classpathentry kind="con" path="org.eclipse.pde.core.requiredPlugins" />
  <classpathentry kind="src" path="src" />
  <classpathentry kind="output" path="target/classes" />
  <classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-11">
    <attributes>
      <attribute name="module" value="true" />
      <attribute name="limit-modules" value="java.base,java.compiler,java.rmi" />
    </attributes>
  </classpathentry>
</classpath>
```

Now, I have the module builds randomly failing and randomly succeeding.

Can someone try to add the above .classpath files to the failing modules and try to obtain a consistent build outcome

**Comment by berryma4** [comment]
What's the current issue, still this?
https://bugs.eclipse.org/bugs/show_bug.cgi?id=536928

**Comment by willrogers** [comment]
It was premature to update the version of Eclipse to 2019-06 because it wants to use batik 1.11, not the 1.10 that we've just made to work. So I will revert to 2019-03.

**Comment by willrogers** [comment]
@shroffk presumably this PR is obsolete.

**Comment by shroffk** [comment]
Yes, 
Many elements of this are already included in the master. I had kept this around as a comparison.

**Pull request closed without merging**
