### PR TITLE
Pvtab egu 1625

### LINKED ISSUE #1625: PVTable 'EGU' handling
The PV Table displays values with units, for example "3 mm".
It also allows entering a new value in that value cell, but that entered value must NOT include the units because the string is currently written as entered.

Ideally, the PV table would know that it had added the " mm" units and remove them when sending an entered value back to the PV.

### PR DESCRIPTION
**Pull request by kasemir**
Fixes #1625

### CODE REVIEW

**Comment by kasemir** [comment]
Wait: Will also fix
```
Warning: NLS missing message: InformationPopup_DelConfHeader in: org.csstudio.display.pvtable.messages
```
in this pull request

**Comment by kasemir** [comment]
OK, added texts that had only been in the Fench version.

**Comment by berryma4** [comment]
done?

**Comment by kasemir** [comment]
Yes.

**Pull request merged**
