### PR TITLE
#2437 adding example editor which open files in phoebus

### PR DESCRIPTION
**Pull request by shroffk**
Examples for how to integrated phoebus applications as the editor.

### CODE REVIEW

**Comment by shroffk** [comment]
@berryma4 can we close this...
just to clean up our list of open PRs

**Comment by berryma4** [comment]
merge or close?

**Comment by shroffk** [comment]
merge

**Comment by berryma4** [comment]
Would you mind approving 2560, it exceeds the timeout limit. damn this build.

**Comment by shroffk** [comment]
ok...
can we merge this first.

**Comment by berryma4** [comment]
I will approve this one as soon as the other is merged. (even though I don't see merge conflicts happening)

**Comment by berryma4** [comment]
checkOnlyDescFaultTextParsin(org.csstudio.logbook.olog.property.fault.FaultAdapterTest)  Time elapsed: 0 s

Results:

Errors: 
  FaultConfigurationParsingTest.parserTest:24 Â» JAXB Implementation of JAXB-API ...

**Comment by berryma4** [comment]
I thought I fixed all the jaxb spots. Was this previously not in the build?

**Pull request merged**
