### PR TITLE
Diirt integration

### PR DESCRIPTION
**Pull request by shroffk**
Pull request into master for the 4.2 release #1356 

Review:
@berryma4 @kasemir @willrogers @utzeln  

Note:
Delete the remote branch after the merge is approved.

### CODE REVIEW

**Comment by berryma4** [comment]
Did you get the pull request into the general product yet?

**Comment by shroffk** [comment]
https://github.com/ControlSystemStudio/org.csstudio.product/pull/13

**Comment by berryma4** [comment]
yes, I was thinking we should have the feature and the config files in the root files feature

**Comment by shroffk** [comment]
Ok, 
Finished merging again

**Comment by shroffk** [comment]
@berryma4 the config files are part of the o.c.product repo

**Comment by shroffk** [comment]
Do Not Merge
This pull request is now not valid.

**Pull request closed without merging**
