### PR TITLE
SVG animation

### PR DESCRIPTION
**Pull request by jbobnar**
Implementation of animated SVG images.

### CODE REVIEW

**Comment by berryma4** [comment]
@shroffk @kasemir BOY changes that need another tester.
Thank you!

**Comment by kasemir** [comment]
org.csstudio.swt.widgets/src/org/csstudio/swt/widgets/figures/ImageBoolButtonFigure.java removes 'synchronized' keywords. I don't know how the synchronization is supposed to work there. Maybe that's fine. If in doubt, I'd feel better with added thread-safe copies. Instead of just removing the synchronized from dispose:
```
public /* no more synchronized  */ void dispose() {
    // Can onImage change while this code is running?
    if (onImage != null && !onImage.isDisposed()) {
        onImage.dispose();
        onImage = null;
```

.. do this ..:

```
public void dispose() {
    final SymbolImage copy;
    synchronized (this)
    {
      copy = onImage;
      onImage = null;
     }
     if (copy != null && ! copy.isDisposed())
		copy.dispose();
```

**Comment by arnaudf-iter** [comment]
```ImageBoolButtonFigure``` was updated to use ```org.csstudio.swt.widgets.symbol.SymbolImage``` and so, be able to display SVG, GIF & PNG the same way as Symbols Widgets. To do this, I copy/pasted a lot of methods from ```org.csstudio.opibuilder.widgets.symbol.multistate.CommonMultiSymbolFigure``` which already has these 'synchronized' keywords for no particular reason as far as I know.

We shouldn't have any issues with the methods not being synchronized. Everything should be called from the GUI thread. So any synchronization is redundant.

**Comment by berryma4** [comment]
does this close #599 ?

**Comment by arnaudf-iter** [comment]
Yes, done.

**Pull request merged**
