### PR TITLE
Archiver Appliance and schema

### PR DESCRIPTION
**Pull request by jbobnar**
Strip the protocol schema from the name before fetching the data. 
Solves #1655

### CODE REVIEW

**Comment by berryma4** [comment]
Thank you!

**Comment by kasemir** [comment]
See discussion on #1655. I don't think this really solves the issue. Going forward, we need to allow both "ca://fred" and "pva://fred" because both can be on the network, both are valid, and both are archived.

If the archive appliance is for now limited to ca:// (is it? I thought it uses the PVManager?), then it's OK for now to strip the ca:// from PVs in the appliance reader, and report an error on any other prefix. The plan should then be to support both ca:// and pva:// in the future. Simply stripping the prefix and effectively returning ca://fred when asked for pva://fred seems wrong.

**Comment by jbobnar** [comment]
Appliance is not using pvmanager. It uses the (modified) thin PV layer, that used to exist in CSS before pv manager:
https://github.com/slacmshankar/epicsarchiverap/tree/master/src/main/org/epics/archiverappliance/engine/pv
Adding a ca://fred or pva://fred will result in forever disconnected PV.

> See discussion on #1655. I don't think this really solves the issue.

It depends on whether ca://fred and pva://fred is the same thing or not. If the PV is uniquely defined by its name (doesn't matter if it is pva or ca) than the clients that request data from the archiver do not need to know how the archiver obtained the data. They know that the server has the PV 'fred', which is of type 'X'. If they archiver gathered the data via channel access, pvaccess, http, tango or tine doesn't really matter to the client.

**Comment by kasemir** [comment]
Well, there is a EPICS_V4_PV as well as EPICS_V3_PV in that PV layer, so clearly a motion has been made towards supporting both protocols. Maybe it plans to distinguish between the two by means other than a ca:// resp. pva:// prefix, then it'll be up to the CSS appliance.reader to map the prefix to whatever the archive appliance uses to fetch the corresponding data.
Simply stripping the prefix may well be a good workaround for now, but it can't be the long term solution.

**Pull request merged**
