### PR TITLE
XY Graph interaction: zooming in/out, panning, Scrolling enable/disable

### PR DESCRIPTION
**Pull request by rosarp**
Fix for #2003

### CODE REVIEW

**Comment by berryma4** [comment]
This is failing on checkstyle, please fix.

**Comment by rosarp** [comment]
Changes were in scan plugin. I have fixed them for this branch.

**Comment by berryma4** [comment]
You can remove your last commit, those changes are in master.  You just need to resync master to your branch.

**Comment by rosarp** [comment]
@berryma4 
I did merge latest changes from master.
Now the error is :  The job exceeded the maximum time limit for jobs, and has been terminated.

**Comment by berryma4** [comment]
TravisCI has increase the timeout for us.  Thank you for your patience.

**Pull request merged**
