### PR TITLE
Add simplepv.pvmanager into opibuilder feature.

### PR DESCRIPTION
**Pull request by willrogers**
Otherwise pvmanager is not recognised by OPIBuilder.

@kasemir @shroffk is this the correct feature to add it into?

### CODE REVIEW

**Comment by berryma4** [comment]
I like the idea of this being in the main opibuilder feature

**Comment by shroffk** [comment]
The simplepv is currently not used by any other applications, so it sort of makes sense to include this in the opibuilder.

We have 2 implementations simplepv.pvmanager and simplepv.vtypepv...should they have their own features?

**Comment by berryma4** [comment]
That's why I like it.  This give preference to pvmanager.

**Comment by kasemir** [comment]
I'm with Kunal: Only used by the opibuilder, so add both simplepv.pvmanager and simplepv.vtypepv to an opibuilder feature.

There's also org.csstudio.simplepv.utilitypv, which we should _not_ add, because the older utilitypv doesn't handle all data types and results in added conversions between DBR_* and VType.

**Comment by shroffk** [comment]
@berryma4 can we merge this to proceed with testing

**Pull request merged**
