### PR TITLE
Perspectives

### PR DESCRIPTION
**Pull request by willrogers**
Don't merge!

This is a prototype method for importing and exporting perspectives **including** OPIViews.  There's a lot to talk about here so I thought I could open a pull request for discussion.

This depends on functionality that is due for release on Friday: https://www.eclipse.org/eclipse/development/plans/freeze_plan_4_5_2.php.

Most of this is in a separate plugin / feature, so can be included or not by individual sites.  There is some extra code in `OPIView.java` needed to restore state in some cases.

See #1574 and #1398.

@kasemir @shroffk @berryma4

### CODE REVIEW

**Comment by kasemir** [comment]
This would be huge!!
Can we have a hangout where you explain/demo?
Friday, March 26, the usual CSS time of 9:00 Eastern US, 14:00 London?

**Comment by shroffk** [comment]
March 26th or Feb 26th?

**Comment by willrogers** [comment]
I have a meeting on Friday at 14:00.

11:00 Eastern / 16:00 London would be ok.

**Comment by kasemir** [comment]
I'm OK with Feb 26, 11:00 Eastern / 16:00 London

**Comment by berryma4** [comment]
I'm in!

**Comment by kasemir** [comment]
I'll create hangout invite

**Comment by kasemir** [comment]
Notes from hangout:

"Perspective" only contains information for "opiView:1234", "opiview:3455".
The MPart info has the state, i.e. the *.opi path, macros etc. for each of these views.
So when just the "Perspective" is saved, we get a blank "opiView:1234" and "opiview:3455" but they lost their state.

Will moved the 'state' into the MPerspective, so it'll be saved/restored.

Eclipse 4.5.2 does save & load the perspectives as part of a load/save preferences mechanism using *.epf files. Eclipse does _not_ have a "save this perspective" or "load that perspective" mechanism for individual perspectives.

So Will extended the "Save As" Perspective to also store that one perspective as a file. For now that's done silently in the workspace (data) area. User is not prompted for path, no way to change the path.

In addition, there's a new menu entry CSS/Utility/Load Perspective to load just one such file.

Will demo'ed it, works great.

--> We can load & save selected perspectives.
--> Needs 4.5.2 to actually "work". Our pom.xml point to 4.5, which includes 4.5.2 since that's become available.
--> Means that we will have to support this as Eclipse changes.

**Comment by kasemir** [comment]
Idea by Kunal:
On startup, load all saved perspectives from a directory.

**Comment by willrogers** [comment]
@kasemir @shroffk where should perspectives be loaded from at startup?  Should this be saved in a preference?

**Comment by berryma4** [comment]
Could we follow the others, a preference with the default being in the
configuration directory?

**Comment by willrogers** [comment]
Which others are you thinking of?

**Comment by berryma4** [comment]
Diirt, then the common product also has the preference.ini, and jaas
files.  I move these for debian (etc/cs-studio), but it's a nice default.

**Comment by kasemir** [comment]
A default location inside the product makes sense as a default, because that way you can package your product with some "built in" perspectives that everybody gets with the product download, and they're then available regardless of workspace.

For my production setup on beamlines, however, the actual location will be outside of the product.
Several versions of CSS will all need to point to some common directory for the perspectives.

The workspace seems the least useful place.

==> Default to configuration area, with preference to point it to any directory.

**Comment by willrogers** [comment]
OK there's now a preference option and perspectives will be loaded from that location at startup.

**Comment by willrogers** [comment]
I haven't tested on Windows and I haven't tested with HTTP OPIs, because these are both a bit less convenient for me.

**Comment by willrogers** [comment]
@berryma4 @kasemir there is already a perspectives preference page in "General | Perspectives".

I added a "CSS Core | Perspectives" preference page.

It's definitely confusing to have them in different places, but possibly confusing to have the CSS one in the general section.

Should I move my preference page to "General | Perspective Loading"?  I think so.

**Comment by berryma4** [comment]
Tough question, but I agree with "General | Perspective Loading"

**Comment by willrogers** [comment]
OK - bar further unit tests and any comments people have, I think this branch is ready.

I'll resolve the merge conflicts tomorrow, then either you can:

* wait for further comments
* wait until someone else builds and tests it 
* merge this and we fix any further problems we find on master

**Comment by willrogers** [comment]
A user comment from here is that we need to be able to configure both:

* location from which perspectives are loaded
* location to which perspectives are saved

I'll add the former.

**Comment by willrogers** [comment]
OK I think this is ready to merge.

**Comment by berryma4** [comment]
This is great!!!  Thank you!

**Pull request merged**
