### PR TITLE
o.c.swt.widgets: added caching for symbol images using google guava

### PR DESCRIPTION
**Pull request by berryma4**
#1206

### CODE REVIEW

**Comment by berryma4** [comment]
@kasemir @shroffk @jbobnar @utzeln 
Could you please check these changes.
It only goes to the cache if it's not in the workspace.

**Comment by shroffk** [comment]
1. The connection cleanup works, there are no more leaked reader and writers from the linking container.

Problems: 
1. referencing groups in linking containers is broken
2. the connections between widgets inside linking containers no longer works (but maybe this is ok)

**Comment by kasemir** [comment]
Replaced tabs with spaces and updated the javadoc since pathToInputStream() no longer handles workspace files.

**Comment by berryma4** [comment]
Thank you.

**Pull request merged**
