### PR TITLE
Issue #2437

### PR DESCRIPTION
**Pull request by shroffk**
Work in progress. Do not merge

### CODE REVIEW

**Comment by willrogers** [comment]
These changes don't directly affect me so merge when you're happy.

**Comment by berryma4** [comment]
Sounds like a consensus. Merge this, and new pull requests for new features.

**Comment by claudio-rosati** [comment]
From a user point of view, what will appear on the CS-Studio UI?

**Comment by willrogers** [comment]
This pull request introduced a bunch of whitespace errors that broke my build. I guess we don't have the Travis build at the moment to catch these.

**Comment by berryma4** [comment]
My fault, yes it looks like the Travis/GitHub pull request stopped being
part of the "check marked okay". I'll look into this.

**Comment by shroffk** [comment]
Sorry, 
It seems like with my installation of oxygen I did not have eclipse-cs plugin available bu default, I usually just carry over the preferences from my old workspace but this time I had to install it separately.

Even after it is installed and it seems to not apply to xml files...a resource described in stylesheet as one to be checked for tabs and whitespaces.
In the example below I added tabs and whitespaces and tried "check code with checkstyle" but got no warnings while there are clearly 2 issues.
image

I would hope the IDE warns me of these violations before they are committed and break builds...

**Pull request merged**
