### PR TITLE
o.c.trends.databrowser2: archive search view double-click

### PR DESCRIPTION
**Pull request by willrogers**
This opens the data browser editor with a double click in the search
view, instead of (or as well as) being able to use the right-click
menu.

@kasemir @berryma4

### CODE REVIEW

**Comment by kasemir** [comment]
Please check
````
 +                    Activator.getLogger().log(Level.WARNING, "Failed to open data browser", this); 
````

I think it should be " "Failed to open data browser", ex);" to log the exception.

**Comment by berryma4** [comment]
sorry, I made wit the change #1525

**Comment by berryma4** [comment]
closes #1521

**Comment by willrogers** [comment]
Thanks Eric and Kay.

**Pull request merged**
