### PR TITLE
2172 Separators in web menu

### PR DESCRIPTION
**Pull request by claudio-rosati**
'|' character can be used to add separators between web menu items.

Note: Docbook updated in [org.csstudio.docbook#11](https://github.com/ControlSystemStudio/org.csstudio.docbook/pull/11).

### CODE REVIEW

**Comment by claudio-rosati** [comment]
Is not that only. The type returned by the method is different, and a different menu item insertion method is called depending on separator or action. 
I apologize for changing the formatting but this helped me to better understand the code and then how to proceed.

**Comment by berryma4** [comment]
Could you add an issue ticket.

**Comment by claudio-rosati** [comment]
A ticket for what? I don't understand sorry

**Comment by berryma4** [comment]
All pull requests need an issue which relates to them.

https://drive.google.com/file/d/0B_ikNAN_jxjPR0U4WllDeUNJRFU/view

This allows a single issue ticket to see which branches the fix has been applied to, and allows discussion when more pull requests are needed.

**Comment by claudio-rosati** [comment]
Understood.
Thank you very much.

**Comment by claudio-rosati** [comment]
Done: #2172

**Pull request merged**
