### PR TITLE
Diirt integration

### PR DESCRIPTION
**Pull request by shroffk**
Redoing the pull request again into master for the 4.2 release #1356

Please address this pull request before merging other pull requests since this touches quite a few files and accepting other pull request might render this one unacceptable.

Review:
@berryma4 @kasemir @willrogers @utzeln

Note:
Delete the remote branch after the merge is approved.

### CODE REVIEW

**Comment by kasemir** [comment]
I agree that this is a large change that we should complete before merging something else.

Should we merge this, then treat what comes up as bugs which we also fix on master?

**Comment by shroffk** [comment]
I think we can merge this and leave master open for awhile (so that people can check if things aren't horribly broken) and then once we have the go ahead we create the 4.2 branch

**Comment by shroffk** [comment]
The Jenkins build need the diirt/p2 repository since things aren't packaged in maven-osgi-bundles

**Comment by berryma4** [comment]
#1171

**Pull request merged**
