### PR TITLE
Fix for the mixed arguments/results table in Service button dialog

### PR DESCRIPTION
**Pull request by boryto**
Tables were switched, so arguments were under results.

### CODE REVIEW

**Comment by boryto** [comment]
#2268

**Comment by shroffk** [comment]
Was this a result of the previous merge?

**Comment by boryto** [comment]
Previous merge (05585afc59) was fix for the dialog, as before the dialog was totally messed-up.  This is additional fix, for the tables of results and arguments were flipped after the merge.  Not sure, but yes this, could be result of previous merge.

**Comment by shroffk** [comment]
ok cool...I am fine with the merge

The form layout has behaved badly on past occasions on various linux windows managers. I think we should try to avoid it.

**Pull request merged**
