### PR TITLE
Travis fix

### PR DESCRIPTION
**Pull request by willrogers**

### CODE REVIEW

**Comment by berryma4** [comment]
Thank you @willrogers

**Comment by berryma4** [comment]
This is my fault:
https://github.com/ControlSystemStudio/cs-studio/commit/412b68ccf86cf6a7a53b4eb807a02c741ee74411#diff-b342b077f69452b5c82b92287def3ee8L2
I removed the set -e when I was testing the timeout errors.

**Comment by willrogers** [comment]
This is now failing on the problem in #2101.

**Comment by berryma4** [comment]
Could you comment out @shroffk test plugin, and he can do a pull request which fixes it on Monday.
org.csstudio.logbook.olog.property.fault.test

**Comment by berryma4** [comment]
@willrogers thank you for all the work.  I'm going to squash this, because that was a lot of odd commits.

**Pull request merged**
