### PR TITLE
Issue #1748

### PR DESCRIPTION
**Pull request by shroffk**
Needs reviewing

### CODE REVIEW

**Comment by berryma4** [comment]
#1748

**Comment by shroffk** [comment]
All the tests in the o.c.alarm.server.test pass except got the filterunit tests which fail with some caj error.

**Comment by berryma4** [comment]
I should not have merged this.
I needed @kasemir to review.
I apologize.  If needed, I will roll back.

**Comment by shroffk** [comment]
don't revert

**Comment by kasemir** [comment]
No worries.
I'll look at the diff later this week, then we'll fix what's needed, no reason to revert.

**Pull request merged**
