### PR TITLE
Alarm Table OPI Widget (#1252)

### PR DESCRIPTION
**Pull request by jbobnar**

### CODE REVIEW

**Comment by jbobnar** [comment]
Sorry for the large number of commits, it is just a lot of history.

The changed files are almost all related to alarm table OPI widget #1252. There is a new plugin and a new feature that includes the plugin. The feature has been added to the alarm repository. By including the feature you can place an alarm table directly on the OPI. The table will show whatever alarm root (or item) is defined by one of the OPI properties.

In OPIEditor, AbstractScriptStore and AbstractWidgetAction I removed a few trailing white spaces, noticed by @willrogers (https://github.com/ControlSystemStudio/cs-studio/issues/1055#issuecomment-119488219).

**Comment by willrogers** [comment]
Thanks for fixing the whitespace.

**Comment by berryma4** [comment]
@kasemir there are some beast changes, are you okay with the merge.

**Comment by kasemir** [comment]
Fine, go ahead

**Pull request merged**
