### PR TITLE
Alarm Table Widget >> if Filter Item does not exist, it should display

### PR DESCRIPTION
**Pull request by rosarp**
Fix for #1995

### CODE REVIEW

**Comment by berryma4** [comment]
@shroffk

**Comment by berryma4** [comment]
@utzeln I believe you own this widget.  are you okay with the changes?

**Comment by berryma4** [comment]
@utzeln I believe you own this widget.  are you okay with the changes?

**Comment by utzeln** [comment]
Yes I am OK with the changes. Thanks.

**Pull request merged**
