### PR TITLE
move to tycho 0.23.1, removed rap from build, o.c.diag.probe: fixed p…

### PR DESCRIPTION
**Pull request by berryma4**
…eriod_format error

#1064
@jbobnar I had to remove some rap features so it would compile.
I was getting this error again:
https://github.com/ControlSystemStudio/cs-studio/issues/788

### CODE REVIEW

**Comment by jbobnar** [comment]
OK. I'll have a look at RAP (there are a few other things that need to be updated besides features).

**Comment by berryma4** [comment]
Thank you!

**Comment by jbobnar** [comment]
There is an "extra" folder in the cs-studio-thirdparty which contains rap.draw2d and rap.gef plugins (plus a few others): https://github.com/css-iter/cs-studio-thirdparty/tree/master/extras/plugins
All these plugins are obsolete and should not be used. However, tycho is eager to take the highest version number of any plugin it uses. For some reason the latest rap.gef and rap.draw2d have the version numbers 0.1.0. This results in using the extra plugins instead of the real latest ones.

Could you remove the entire extra folder from the thirdparty repository (or at least all rap plugins)?

**Comment by kasemir** [comment]
Jaka, I think right now you know best how to build the RAP products. If you don't need those extra plugins, or on the contrary, they actually cause trouble, by all means remove them.

**Comment by berryma4** [comment]
I removed the "extra" folder in thirdparty.  I will always be more than happy to remove anything from maven-osgi-bundles or thirdparty.

**Pull request merged**
