### PR TITLE
Diirt VImage update

### PR DESCRIPTION
**Pull request by kasemir**
To be merged after https://github.com/diirt/diirt/pull/74 to use updated VImage.

### CODE REVIEW

**Comment by berryma4** [comment]
I'm not sure why one is failing with:
```java
ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:1.0.0:compile (default-compile) on project org.csstudio.vtype.pv: Compilation failure: Compilation failure:
[ERROR] /home/travis/build/ControlSystemStudio/cs-studio/core/base/base-plugins/org.csstudio.vtype.pv/src/org/csstudio/vtype/pv/pva/VImageForNTNDArray.java:[16]
[ERROR] import org.diirt.vtype.VImageDataType;
[ERROR] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] The import org.diirt.vtype.VImageDataType cannot be resolved
[ERROR] /home/travis/build/ControlSystemStudio/cs-studio/core/base/base-plugins/org.csstudio.vtype.pv/src/org/csstudio/vtype/pv/pva/VImageForNTNDArray.java:[17]
[ERROR] import org.diirt.vtype.VImageType;
[ERROR] ^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by kasemir** [comment]
It depends on the new VImage (diirt/diirt#74). It won't compile until diirt has been updated.

**Comment by shroffk** [comment]
I am waiting on getting the go ahead from @claudio-rosati

**Comment by kasemir** [comment]
diirt/diirt#74 has been updated, so now this should compile.

**Comment by berryma4** [comment]
restarted build

**Comment by shroffk** [comment]
can we have the diirt version updated to 3.1.6 in the pom.xmls

<diirt.version>3.1.5</diirt.version>

**Comment by kasemir** [comment]
This pull request started in early May.
Should we first merge #2231, and then I sync this one back up with master?

**Comment by kasemir** [comment]
I've updated the pom.xml as you suggested for the other pull request, 2231, and also merged up with the latest master.

**Comment by kasemir** [comment]
Merged with master once more

**Comment by kasemir** [comment]
Thanks!

**Pull request merged**
