### PR TITLE
Influxdb archive app

### PR DESCRIPTION
**Pull request by ajcarpente42**

### CODE REVIEW

**Comment by kasemir** [comment]
Yes, would like to work towards getting this merged.
Not because it's done, but because we have about 6 months of work in this.
There is an archive engine, the data browser can read, and Amanda just added 'optimized' readout that fetches a reduced number of min/max/average instead of every raw sample, plus there's a good start with retention. For now you still need to manually configure the retention policy AND the continuous query in the database. Might stay that way, because you do need to plan that ahead of time, can't just change retention when you have already collected months worth of data.
The engine can write to the retention policy, and the retrieval does look in the retention namespace and the one reduced by the continuous query.
So you can write every say 10 seconds, and after a few days that's replaced by a 1 hour average.

We're trying a demo setup here and will then describe how to do that.

Meanwhile, there tends to be a strange build error with jenkins:
Cannot find org.influx.java 2.6.0, but that's in maven-osgi-bundles since June 20:
https://github.com/ControlSystemStudio/maven-osgi-bundles/blob/master/repository/pom.xml
````
<artifact>
  <id>org.influxdb:influxdb-java:2.6</id>
  <instructions>
    <Require-Bundle>com.squareup.retrofit2.converter-moshi,com.squareup.okhttp3.logging-interceptor</Require-Bundle>
  </instructions>
</artifact>
````

**Comment by kasemir** [comment]
Travis still ends with
````
Missing requirement: org.csstudio.archive.config.influxdb 4.2.1.qualifier requires 'bundle org.influxdb.java 2.6.0' but it could not be found
````

I don't understand, builds and runs fine here when using the 'master' of the maven-osgi-bundles sources.

**Comment by berryma4** [comment]
Seems to be an error in the maven-osgi-bundles build:
https://travis-ci.org/ControlSystemStudio/maven-osgi-bundles/builds/245503114#L4027

I'm not sure why it still  passes as a good build.

**Comment by berryma4** [comment]
I'm restarting the build.

**Comment by berryma4** [comment]
https://github.com/reficio/p2-maven-plugin/issues/81
Upgrading p2-maven-plugin to version 1.2.0

**Comment by berryma4** [comment]
https://github.com/ControlSystemStudio/maven-osgi-bundles/pull/46
Kay, could you approve the pull request.

**Comment by berryma4** [comment]
I found another problem:
https://github.com/ControlSystemStudio/maven-osgi-bundles/pull/47
https://github.com/ControlSystemStudio/cs-studio-thirdparty/pull/42
Kay, could you approve these pull requests?

**Comment by berryma4** [comment]
Current checkstlye errors after the depends repo fix:
```java
/home/travis/build/ControlSystemStudio/cs-studio/applications/appunorganized/appunorganized-plugins/org.csstudio.email/src/org/csstudio/email/EMailSender.java:17:1: warning: Import from illegal package - sun.net.smtp.SmtpClient.
/home/travis/build/ControlSystemStudio/cs-studio/applications/apputil/apputil-plugins/org.csstudio.apputil/src/org/csstudio/apputil/args/BooleanOption.java:20: error: Trailing whitespaces
/home/travis/build/ControlSystemStudio/cs-studio/applications/archive/archive-plugins/org.csstudio.archive.config/src/org/csstudio/archive/config/XMLImport.java:57: error: Trailing whitespaces
/home/travis/build/ControlSystemStudio/cs-studio/applications/archive/archive-plugins/org.csstudio.archive.config/src/org/csstudio/archive/config/XMLImport.java:112: error: Trailing whitespaces
/home/travis/build/ControlSystemStudio/cs-studio/applications/archive/archive-plugins/org.csstudio.archive.writer.test/test/org/csstudio/archive/writer/influxdb/DownsamplingDemo.java:5:8: error: Unused import - java.time.Period.
/home/travis/build/ControlSystemStudio/cs-studio/applications/archive/archive-plugins/org.csstudio.archive.writer.test/test/org/csstudio/archive/writer/influxdb/DownsamplingDemo.java:37: error: Trailing whitespaces
/home/travis/build/ControlSystemStudio/cs-studio/applications/archive/archive-plugins/org.csstudio.archive.writer.test/test/org/csstudio/archive/writer/influxdb/DownsamplingDemo.java:69: error: Trailing whitespaces
/home/travis/build/ControlSystemStudio/cs-studio/applications/archive/archive-plugins/org.csstudio.archive.writer.test/test/org/csstudio/archive/writer/influxdb/DownsamplingDemo.java:87: error: Trailing whitespaces
/home/travis/build/ControlSystemStudio/cs-studio/applications/archive/archive-plugins/org.csstudio.archive.writer.test/test/org/csstudio/archive/writer/influxdb/DownsamplingDemo.java:96: error: Trailing whitespaces
/home/travis/build/ControlSystemStudio/cs-studio/applications/archive/archive-plugins/org.csstudio.archive.writer.test/test/org/csstudio/archive/writer/influxdb/DownsamplingDemo.java:102: error: Trailing whitespaces
/home/travis/build/ControlSystemStudio/cs-studio/applications/archive/archive-plugins/org.csstudio.archive.writer.test/test/org/csstudio/archive/writer/influxdb/DownsamplingDemo.java:124: error: Trailing whitespaces
/home/travis/build/ControlSystemStudio/cs-studio/applications/archive/archive-plugins/org.csstudio.archive.writer.test/test/org/csstudio/archive/writer/influxdb/DownsamplingDemo.java:129: error: Trailing whitespaces
/home/travis/build/ControlSystemStudio/cs-studio/applications/archive/archive-plugins/org.csstudio.archive.writer.test/test/org/csstudio/archive/writer/influxdb/DownsamplingDemo.java:166: error: Trailing whitespaces
/home/travis/build/ControlSystemStudio/cs-studio/applications/archive/archive-plugins/org.csstudio.archive.writer.test/test/org/csstudio/archive/writer/influxdb/DownsamplingDemo.java:184: error: Trailing whitespaces
/home/travis/build/ControlSystemStudio/cs-studio/applications/archive/archive-plugins/org.csstudio.archive.writer.test/test/org/csstudio/archive/writer/influxdb/DownsamplingDemo.java:213: error: Trailing whitespaces
/home/travis/build/ControlSystemStudio/cs-studio/applications/archive/archive-plugins/org.csstudio.archive.writer.test/test/org/csstudio/archive/writer/influxdb/DownsamplingDemo.java:218: error: Trailing whitespaces
/home/travis/build/ControlSystemStudio/cs-studio/applications/archive/archive-plugins/org.csstudio.archive.influxdb/src/org/csstudio/archive/influxdb/InfluxDBQueries.java:7:8: error: Unused import - java.util.HashMap.
/home/travis/build/ControlSystemStudio/cs-studio/applications/archive/archive-plugins/org.csstudio.archive.influxdb/src/org/csstudio/archive/influxdb/InfluxDBQueries.java:9:8: error: Unused import - java.util.Map.
/home/travis/build/ControlSystemStudio/cs-studio/applications/archive/archive-plugins/org.csstudio.archive.influxdb/src/org/csstudio/archive/influxdb/InfluxDBQueries.java:81: error: Trailing whitespaces
/home/travis/build/ControlSystemStudio/cs-studio/applications/archive/archive-plugins/org.csstudio.archive.influxdb/src/org/csstudio/archive/influxdb/InfluxDBQueries.java:83: error: Trailing whitespaces
/home/travis/build/ControlSystemStudio/cs-studio/applications/archive/archive-plugins/org.csstudio.archive.influxdb/src/org/csstudio/archive/influxdb/InfluxDBQueries.java:87: error: Trailing whitespaces
/home/travis/build/ControlSystemStudio/cs-studio/applications/archive/archive-plugins/org.csstudio.archive.influxdb/src/org/csstudio/archive/influxdb/MetaTypes.java:245:9: error: Line contains a tab character.
/home/travis/build/ControlSystemStudio/cs-studio/applications/archive/archive-plugins/org.csstudio.archive.influxdb/src/org/csstudio/archive/influxdb/MetaTypes.java:249:1: error: Line contains a tab character.
/home/travis/build/ControlSystemStudio/cs-studio/applications/archive/archive-plugins/org.csstudio.archive.influxdb/src/org/csstudio/archive/influxdb/MetaTypes.java:250:1: error: Line contains a tab character.
/home/travis/build/ControlSystemStudio/cs-studio/applications/archive/archive-plugins/org.csstudio.archive.influxdb/src/org/csstudio/archive/influxdb/MetaTypes.java:251:1: error: Line contains a tab character.
/home/travis/build/ControlSystemStudio/cs-studio/applications/archive/archive-plugins/org.csstudio.archive.influxdb/src/org/csstudio/archive/influxdb/MetaTypes.java:252:1: error: Line contains a tab character.
/home/travis/build/ControlSystemStudio/cs-studio/applications/archive/archive-plugins/org.csstudio.archive.influxdb/src/org/csstudio/archive/influxdb/MetaTypes.java:253:1: error: Line contains a tab character.
/home/travis/build/ControlSystemStudio/cs-studio/applications/archive/archive-plugins/org.csstudio.archive.reader.influxdb.raw/src/org/csstudio/archive/reader/influxdb/raw/InfluxDBRawReader.java:26:1: warning: Redundant import from the same package - org.csstudio.archive.reader.influxdb.raw.AveragedValueIterator.
/home/travis/build/ControlSystemStudio/cs-studio/applications/archive/archive-plugins/org.csstudio.archive.reader.influxdb/src/org/csstudio/archive/reader/influxdb/AggregatedChunkReader.java:4:8: error: Unused import - java.util.List.
/home/travis/build/ControlSystemStudio/cs-studio/applications/archive/archive-plugins/org.csstudio.archive.reader.influxdb/src/org/csstudio/archive/reader/influxdb/AggregatedChunkReader.java:7:1: warning: Redundant import from the same package - org.csstudio.archive.reader.influxdb.ChunkReader.
/home/travis/build/ControlSystemStudio/cs-studio/applications/archive/archive-plugins/org.csstudio.archive.reader.influxdb/src/org/csstudio/archive/reader/influxdb/AggregatedChunkReader.java:8:8: error: Unused import - org.csstudio.archive.influxdb.MetaTypes.
/home/travis/build/ControlSystemStudio/cs-studio/applications/archive/archive-plugins/org.csstudio.archive.reader.influxdb/src/org/csstudio/archive/reader/influxdb/AggregatedChunkReader.java:9:8: error: Unused import - org.csstudio.archive.influxdb.MetaTypes.MetaObject.
/home/travis/build/ControlSystemStudio/cs-studio/applications/snl/snl-plugins/de.desy.language.snl.ui/src/de/desy/language/snl/ui/editor/CompilerOptionsService.java:116: warning: The Javadoc {@inheritDoc} tag is not valid at this location.
```

**Comment by berryma4** [comment]
Might have a IPv6 issue:
https://docs.travis-ci.com/user/reference/precise/#Networking
We would need to add:
System.setProperty("java.net.preferIPv4Stack" , "true");

**Comment by berryma4** [comment]
Okay, I just noticed you don't start an influxdb server.  It would be best to mark these as IT tests, and/or add mock sources.

**Comment by kasemir** [comment]
I've disabled the tests

**Pull request merged**
