### PR TITLE
Adding Fault application to logbook module

### PR DESCRIPTION
**Pull request by shroffk**
An application to exploring the use of third party javafx libraries.
@berryma4 - please comment on the appropriate location

### CODE REVIEW

**Comment by berryma4** [comment]
The build seems to be failing though.

**Comment by shroffk** [comment]
@berryma4 I don't understand how it fails to find the branch from which this PR originates?
I ensured that the branch actually exists.

**Comment by berryma4** [comment]
travisci probably doesn't like that your branch name doesn't follow the collaboration rules (issue_.*)  :)

**Comment by berryma4** [comment]
It is strange though, permissions?

**Comment by willrogers** [comment]
It looks like it's trying to fetch the branch from the ControlSystemStudio repo when it's on shroffk.

I don't know why, that's a perfectly normal thing to do.

**Comment by shroffk** [comment]
I will recreate this PR

**Comment by berryma4** [comment]
How strange this is, would you mind pushing the branch to CS-Studio, then pull request from there.

**Comment by shroffk** [comment]
I thought a new PR would clarify the confusion but it still seems to be looking for the branch in the main repo instead of my fork.

As far as I am aware I did not do anything different with this branch.

**Pull request merged**
