### PR TITLE
1996 rap build

### LINKED ISSUE #1996: RAP for CSS 4.4 opibuilder
A build of the RAP product against the CSS 4.4 p2 repository doesn't start with an error
> Caused by: java.lang.ClassNotFoundException: org.eclipse.swt.SWTError cannot be found by org.eclipse.ui.workbench_3.107.1.v20160120-2131

*swt probably shouldn't be there, so I compared the installed plugins and I found a number of potentially important differences between 4.3 and 4.4.

> org.eclipse.swt
> org.eclipse.swt.gtk.linux.x86
> org.eclipse.text
> org.eclipse.ui
> org.eclipse.ui.ide
> org.eclipse.ui.workbench

are in the 4.4 war, but not in 4.3.

While trying to find out what is pulled in first in the dependency chain, I came across this commit as a possible source: https://github.com/ControlSystemStudio/cs-studio/commit/79b95e1cb0bd95495c3dfdd6c7c78d50869db252. This brings org.eclipse.ui.ide to the opibuilder dependency list when before it was only used by the editor.

### PR DESCRIPTION
**Pull request by willrogers**
@MichaelRitzert @kasemir here is a pull request that attempts to resolve #1996.

I cannot compile RAP, so I don't know that I've done the right thing for the RAP side of this - it may be necessary to return null and handle it rather than throwing the exception.

### CODE REVIEW

**Comment by kasemir** [comment]
I cannot compule for RAP, either. @MichaelRitzert or @utzeln?

**Comment by MichaelRitzert** [comment]
I compiled the WebOPI against core and applications from @kasemir 's branch, and at first sight it looks good. That is, it starts and displays OPIs as expected.

**Comment by MichaelRitzert** [comment]
The databrowser is strange, however. It seems it renders for a canvas that is much larger than the browser window.

**Comment by willrogers** [comment]
That _shouldn't_ be to do with these changes, but that doesn't mean something hasn't changed elsewhere.

The most likely problem from these changes is you get an uncaught exception either:

* on right click
* on right click on an opi in a linking container

... but I don't really know how RAP works ...

**Comment by MichaelRitzert** [comment]
https://ufile.io/ad724 is the .war file.

**Comment by MichaelRitzert** [comment]
I would also guess that is's some other changes from older CSS. I couldn't test earlier 4.4, so this is quite likely.
I just got an illegal thread exception. I'll see if I can find it in some log.

**Comment by MichaelRitzert** [comment]
Here it is. Reliable happens for one specific OPI. Unfortunately it includes other OPIs in Linking Containers, etc, so it's not easy to attach it here. I'll see if I can reduce it.

```
org.eclipse.swt.SWTException:
 Invalid thread access
	at org.eclipse.swt.SWT.error(SWT.java:3658)
	at org.eclipse.swt.SWT.error(SWT.java:3581)
	at org.eclipse.swt.SWT.error(SWT.java:3552)
	at org.eclipse.swt.widgets.Display.error(Display.java:2308)
	at org.eclipse.swt.widgets.Display.checkDevice(Display.java:2290)
	at org.eclipse.swt.graphics.Device.getSystemFont(Device.java:147)
	at org.eclipse.swt.graphics.ControlGC.getDefaultFont(ControlGC.java:101)
	at org.eclipse.swt.graphics.GC.setFont(GC.java:163)
	at org.eclipse.draw2d.FigureUtilities.setFont(FigureUtilities.java:369)
	at org.eclipse.draw2d.FigureUtilities.getTextDimension(FigureUtilities.java:99)
	at org.eclipse.draw2d.FigureUtilities.getTextExtents(FigureUtilities.java:146)
	at org.eclipse.draw2d.TextUtilities.getTextExtents(TextUtilities.java:59)
	at org.eclipse.draw2d.Label.calculateTextSize(Label.java:248)
	at org.eclipse.draw2d.Label.getTextSize(Label.java:470)
	at org.eclipse.draw2d.Label.calculateAlignment(Label.java:119)
	at org.eclipse.draw2d.Label.calculateLocations(Label.java:159)
	at org.eclipse.draw2d.Label.getTextLocation(Label.java:443)
	at org.eclipse.draw2d.Label.getTextBounds(Label.java:430)
	at org.csstudio.opibuilder.widgets.figures.MenuButtonFigure.updateLayout(MenuButtonFigure.java:65)
	at org.csstudio.opibuilder.widgets.figures.MenuButtonFigure.setText(MenuButtonFigure.java:27)
	at org.csstudio.opibuilder.widgets.editparts.MenuButtonEditPart.doCreateFigure(MenuButtonEditPart.java:83)
	at org.csstudio.opibuilder.editparts.AbstractBaseEditPart.createFigure(AbstractBaseEditPart.java:295)
	at org.eclipse.gef.editparts.AbstractGraphicalEditPart.getFigure(AbstractGraphicalEditPart.java:494)
	at org.eclipse.gef.editparts.AbstractGraphicalEditPart.addChildVisual(AbstractGraphicalEditPart.java:208)
	at org.eclipse.gef.editparts.AbstractEditPart.addChild(AbstractEditPart.java:211)
	at org.eclipse.gef.editparts.AbstractEditPart.refreshChildren(AbstractEditPart.java:781)
	at org.csstudio.opibuilder.editparts.AbstractContainerEditpart.refreshChildren(AbstractContainerEditpart.java:320)
	at org.eclipse.gef.editparts.AbstractEditPart.refresh(AbstractEditPart.java:726)
	at org.eclipse.gef.editparts.AbstractGraphicalEditPart.refresh(AbstractGraphicalEditPart.java:644)
	at org.eclipse.gef.editparts.AbstractEditPart.addNotify(AbstractEditPart.java:253)
	at org.eclipse.gef.editparts.AbstractGraphicalEditPart.addNotify(AbstractGraphicalEditPart.java:223)
	at org.eclipse.gef.editparts.AbstractEditPart.addChild(AbstractEditPart.java:212)
	at org.eclipse.gef.editparts.AbstractEditPart.refreshChildren(AbstractEditPart.java:781)
	at org.csstudio.opibuilder.editparts.AbstractContainerEditpart.refreshChildren(AbstractContainerEditpart.java:320)
	at org.eclipse.gef.editparts.AbstractEditPart.refresh(AbstractEditPart.java:726)
	at org.eclipse.gef.editparts.AbstractGraphicalEditPart.refresh(AbstractGraphicalEditPart.java:644)
	at org.eclipse.gef.editparts.AbstractEditPart.addNotify(AbstractEditPart.java:253)
	at org.eclipse.gef.editparts.AbstractGraphicalEditPart.addNotify(AbstractGraphicalEditPart.java:223)
	at org.eclipse.gef.editparts.AbstractEditPart.addChild(AbstractEditPart.java:212)
	at org.eclipse.gef.editparts.AbstractEditPart.refreshChildren(AbstractEditPart.java:781)
	at org.csstudio.opibuilder.editparts.AbstractContainerEditpart.refreshChildren(AbstractContainerEditpart.java:320)
	at org.eclipse.gef.editparts.AbstractEditPart.refresh(AbstractEditPart.java:726)
	at org.eclipse.gef.editparts.AbstractGraphicalEditPart.refresh(AbstractGraphicalEditPart.java:644)
	at org.eclipse.gef.editparts.AbstractEditPart.addNotify(AbstractEditPart.java:253)
	at org.eclipse.gef.editparts.AbstractGraphicalEditPart.addNotify(AbstractGraphicalEditPart.java:223)
	at org.eclipse.gef.editparts.AbstractEditPart.addChild(AbstractEditPart.java:212)
	at org.eclipse.gef.editparts.SimpleRootEditPart.setContents(SimpleRootEditPart.java:105)
	at org.eclipse.gef.ui.parts.AbstractEditPartViewer.setContents(AbstractEditPartViewer.java:617)
	at org.eclipse.gef.ui.parts.AbstractEditPartViewer.setContents(AbstractEditPartViewer.java:626)
	at org.csstudio.opibuilder.runmode.OPIRuntimeDelegate.createGUI(OPIRuntimeDelegate.java:234)
	at org.csstudio.opibuilder.runmode.OPIRunner.createPartControl(OPIRunner.java:86)
	at org.eclipse.ui.internal.EditorReference.createPartHelper(EditorReference.java:668)
	at org.eclipse.ui.internal.EditorReference.createPart(EditorReference.java:464)
	at org.eclipse.ui.internal.WorkbenchPartReference.getPart(WorkbenchPartReference.java:599)
	at org.eclipse.ui.internal.PartPane.setVisible(PartPane.java:310)
	at org.eclipse.ui.internal.presentations.PresentablePart.setVisible(PresentablePart.java:185)
	at org.eclipse.ui.internal.presentations.util.PresentablePartFolder.select(PresentablePartFolder.java:265)
	at org.eclipse.ui.internal.presentations.util.LeftToRightTabOrder.select(LeftToRightTabOrder.java:64)
	at org.eclipse.ui.internal.presentations.util.TabbedStackPresentation.selectPart(TabbedStackPresentation.java:479)
	at org.eclipse.ui.internal.PartStack.refreshPresentationSelection(PartStack.java:1262)
	at org.eclipse.ui.internal.PartStack.setSelection(PartStack.java:1215)
	at org.eclipse.ui.internal.PartStack.showPart(PartStack.java:1614)
	at org.eclipse.ui.internal.PartStack.add(PartStack.java:508)
	at org.eclipse.ui.internal.EditorStack.add(EditorStack.java:106)
	at org.eclipse.ui.internal.PartStack.add(PartStack.java:494)
	at org.eclipse.ui.internal.EditorStack.add(EditorStack.java:115)
	at org.eclipse.ui.internal.EditorSashContainer.addEditor(EditorSashContainer.java:65)
	at org.eclipse.ui.internal.EditorAreaHelper.addToLayout(EditorAreaHelper.java:225)
	at org.eclipse.ui.internal.EditorAreaHelper.addEditor(EditorAreaHelper.java:213)
	at org.eclipse.ui.internal.EditorManager.createEditorTab(EditorManager.java:775)
	at org.eclipse.ui.internal.EditorManager.openEditorFromDescriptor(EditorManager.java:673)
	at org.eclipse.ui.internal.EditorManager.openEditor(EditorManager.java:633)
	at org.eclipse.ui.internal.WorkbenchPage.busyOpenEditorBatched(WorkbenchPage.java:2855)
	at org.eclipse.ui.internal.WorkbenchPage.busyOpenEditor(WorkbenchPage.java:2763)
	at org.eclipse.ui.internal.WorkbenchPage.access$11(WorkbenchPage.java:2755)
	at org.eclipse.ui.internal.WorkbenchPage$10.run(WorkbenchPage.java:2706)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:66)
	at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:2702)
	at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:2686)
	at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:2669)
	at org.csstudio.opibuilder.runmode.RunModeService.lambda$0(RunModeService.java:183)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:38)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:180)
	at org.eclipse.swt.widgets.Display.runPendingMessages(Display.java:1200)
	at org.eclipse.swt.widgets.Display.safeReadAndDispatch(Display.java:1180)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:1172)
	at org.eclipse.ui.internal.Workbench.runEventLoop(Workbench.java:2733)
	at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:2694)
	at org.eclipse.ui.internal.Workbench.access$5(Workbench.java:2530)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:701)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:684)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:157)
	at org.csstudio.webopi.WorkbenchOPIRuntimeEntryPoint.createUI(WorkbenchOPIRuntimeEntryPoint.java:18)
	at org.eclipse.rap.rwt.internal.lifecycle.RWTLifeCycle.createUI(RWTLifeCycle.java:171)
	at org.eclipse.rap.rwt.internal.lifecycle.RWTLifeCycle$UIThreadController.run(RWTLifeCycle.java:283)
	at java.lang.Thread.run(Thread.java:745)
	at org.eclipse.rap.rwt.internal.lifecycle.UIThread.run(UIThread.java:104)
```

**Comment by kasemir** [comment]
Overall, I think it's great news that it works at all for the most part.

That stack trace doesn't make sense to me.
It shows the RAP UI thread in Workbench.runUI handling UI events, going down quite deep while doing something about some UI part, and then it finds that it's not the UI thread?

**Comment by berryma4** [comment]
merge?

**Comment by willrogers** [comment]
It's difficult to say whether this is correct, but it does move from **not compiling** to **compiling but maybe not perfect**, so I guess you could merge anyway ...

**Pull request merged**
