### PR TITLE
#1520 the configuration directory set during preWindowOpen stage

### PR DESCRIPTION
**Pull request by shroffk**
Temporary solution to the diirt configuration issue.

Could you review
@berryma4 @kasemir @willrogers @jbobnar 

Note:
This should re enable the workspace prompt and allow the config folder to be set via the diirt config folder preference
The xml defined services have not been tested

### CODE REVIEW

**Comment by kasemir** [comment]
Do you know what actually accessed the diirt code and thus caused the diirt Activator to run before the workspace was selected?

In any case, moving the init code from the activator where we're not quite sure when it's invoked to the IWorkbenchWindowAdvisorExtPoint looks good to me.

**Comment by berryma4** [comment]
can we get this on 4.2.x?

**Comment by jbobnar** [comment]
I think this will work, but can you update the diirt p2 repository with the new org.diirt.util plugin. It is mandatory to compile this code.

**Comment by shroffk** [comment]
@jbobnar I am not sure I completely follow? I have merged the associated diirt code into the diirt master branch.

@kasemir I think it was the fact that this plugin also contributed the osgi service descriptions, since the  org.eclipse.equinox.ds start up level is 2 (this is recommended by eclipse)...this in turn searches for and registers all osgi services which results in the activation of the diirt plugin

**Comment by kasemir** [comment]
OK, the service registration sounds plausible. So whatever happens at that time must avoid access to preferences.

**Comment by berryma4** [comment]
4.2.x please?

**Comment by jbobnar** [comment]
@shroffk 
If I execute this:

eclipsec -application org.eclipse.equinox.p2.director -repository http://diirt.download.controlsystemstudio.org/diirt/3.0.1 -list "Q:everything.select(x | x.id == 'org.diirt.util')"

I get the following answer: org.diirt.util=3.0.1.20151009125657
Which means that the p2 repository still has the diirt plugin from 9th October 2015. It should be updated.

**Comment by berryma4** [comment]
Yes, ... @shroffk is having problems with Cloudbees, where the release is done.  The new release will be 3.0.2.  I should have waited to merge this until that was done (with the repo url fix).

I have the 4.2.x branch pull request, cherry picked, coming this morning.

**Comment by shroffk** [comment]
@jbobnar I opened an issue with Cloudbees yesterday...they have escalated the issue but there has been no resolution.
I will wait till afternoon otherwise manually try to update p2 repos.

**Comment by kasemir** [comment]
Thanks for re-enabling the workspace selection, I really needed that!

For what it's worth, I have a cron jobs that install the 'nightly' update of CSS by downloading the basic SNS CSS and then invoking it with `-application org.eclipse.equinox.p2.director` to add optional features. The log shows that the diirt Activator starts even for those:

```
Jan 06, 2016 3:10:50 AM org.csstudio.diirt.util.Activator start
INFO: Starting diirt.util
Installing org.csstudio.sns.feature.ccr.feature.group 4.0.0.201601052111.
```

Not a problem, but shows that there's little control over the service lookup schedule.

**Pull request merged**
