### PR TITLE
Fixing plotbins preference limits.

### PR DESCRIPTION
**Pull request by willrogers**
It isn't possible to enter the special value of '-3' into the databrowser preferences page.

This commit fixes that.

cc @rjwills28

### CODE REVIEW

**Review by kasemir — APPROVED** [review]
Is only -3 allowed? In the phoebus implementation, any negative value represents "abs(N) times the display width", so on a screen that's 1000 pixel wide, -3 would request 3000 bins. https://github.com/ControlSystemStudio/phoebus/blob/2f5de05be5f2827f095097a7963114b17a4efb31/app/databrowser/src/main/resources/databrowser_preferences.properties#L57

**Comment by kasemir** [comment]
Meaning: Maybe "-1",  "-2" or "-4" should also be allowed? Unclear where to draw a limit. "-10" for 10 times the screen resolution would be mad, so limit it to say -5??

**Comment by willrogers** [comment]
So it is. How did we not notice that?

**Comment by willrogers** [comment]
Logic updated to reflect that misunderstanding.

**Comment by kasemir** [comment]
I think that's good!

**Pull request merged**
