### PR TITLE
#2466 Waveform View support Multiple Traces

### PR DESCRIPTION
**Pull request by skyfrench**
Implemented support for multiple traces in WaveformView
- Possible to select more than one PV for display
- Traces are now drawn as a line with no points

Modification made to handle events not coming in at the same time for different plotted PVs:
- the bottom slider remains a linear slider which scrolls through the samples available in the first plotted item (i.e. the single waveform display behaves as it does currently, and when there are multiple traces the first plotted behaves in the same was as it would were it plotted alone)
- the samples plotted for the other item(s) are then the preceding waveform(s) from the timestamp of the waveform sample in the first item

cc @willrogers

### CODE REVIEW

**Comment by kasemir** [comment]
Pull request #2473 was submitted just before this one, and since it has been merged, there are merge conflicts on this one. Please check into using the existing MultipleSelectionCombo class, and the merge conflict. Otherwise I think this is a great idea, thanks!

**Comment by willrogers** [comment]
I resolved the merge conflict and did the simpler list removal. The `MultipleSelectionCombo` sounds useful.

**Comment by kasemir** [comment]
Yes, `MultipleSelectionCombo<ModelItem>` directly holds the model items, removes the need for most of `getModelItems()`.

**Comment by kasemir** [comment]
You're right. With check boxes, you just tick or un-tick the boxes. With the multiselectioncombo, you need to Shift-or-Ctrl-Click until you get carpal tunnel syndrome.
I'm in favor of updating the multiselectioncombo to use combo boxes.
The phoebus version already uses combo boxes, which is probably another indication of their superiority.

**Comment by skyfrench** [comment]
I have committed a modification to the MultipleSelectionCombo to use check boxes. Hopefully it's an improvement on what was there previously?

**Comment by kasemir** [comment]
Does the MultipleSelectionComboDemo still work?

**Comment by skyfrench** [comment]
> Does the MultipleSelectionComboDemo still work?
Yes, I believe it does (comparing behaviour before and after).

**Comment by willrogers** [comment]
That looks nicer. Two comments:

* I don't seem able to get rid of the dropdown by clicking elsewhere (your previous version worked)
* Maybe it should say "- Select items -" or something when nothing is selected

**Pull request merged**
