### PR TITLE
3.2.x

### PR DESCRIPTION
**Pull request by xinyuwu**
The changes I've made can be divided into three sections:
- the additions of products/ASKAP. This is independent and should not effect anyone

- Support for our own bigASub field type. 
bigASub(INP1-X) where The syntax INP1-X is a shortcut for INP001, INP002, ..., INP128
files changed are:
applications/plugins/org.csstudio.diag.epics.pvtree/preferences.ini
applications/plugins/org.csstudio.diag.epics.pvtree/src/org/csstudio/diag/epics/pvtree/FieldParser.java

- The rest of files are related to alarm changes
    * added the ability to disable a whole subtree, this resulted in a database schema change. A database migration script has been included
    * added a new property, notify_escalating_alarms_only (default is false). Unless you explicitly set this property to true, you should not notice any change. If set to true, will only generate a notification if a higher alarm has been triggered. Eg, if alarm is currently MINOR, and if new alarm state is MAJOR, then a notification is generated. But if alarm is currently MAJOR, and if new alarm state MINOR, then no notification is generated.

### CODE REVIEW

**Comment by kasemir** [comment]
Re: Additions of products/ASKAP:
Note that in the new setup on 'master' we removed site-specific stuff from the common repo and instead move those into separate repos like https://github.com/ControlSystemStudio/org.csstudio.nsls2.product, https://github.com/ControlSystemStudio/org.csstudio.dls.product, .. 

Support for our own bigASub field type in org.csstudio.diag.epics.pvtree:
I'd like to review how we can handle site-spec fields in a generic tool.

Alarm changes:
Relates to #944. I'd like to review, then update 'master' with this.


Overall, I'd basically be fine with merging this into the 3.2 branch as is, but then I'm not using that any more.

**Comment by berryma4** [comment]
Usually, we don't like to make feature changes on a stable branch (like requiring someone to upgrade a server and client, ie. the BEAST changes), but bug fixes are always welcome.

Is there anyway we could help move you ahead to 4.1.x?

**Comment by kasemir** [comment]
I'll look at the pvtree and alarm updates and work on separate pull requests for them into 'master'

**Comment by kasemir** [comment]
Regarding the alarm changes to disable a whole subtree, I've implemented this on 'master' (#962) , limiting it to the GUI, no change to alarm server, RDB, XML formats.
GUI can now enable/disable all PVs below an area/system/subsystem.
In addition, alarm tree indicates on area/system/subsystem when at least one PV below is disabled, no matter if that was done via configuration or filter.

The ASKAP products would not be added to 'master' but a site-specific repo.

Functionality left in this pull request is the notify_escalating_alarms_only idea.

**Comment by kasemir** [comment]
With #963 the notify_escalating_alarms_only idea is now available on the 'master' branch.

If we want to leave 3.2.x without new features, we should close this pull request.

**Comment by berryma4** [comment]
thank you.

**Pull request closed without merging**
