### PR TITLE
#1377 fixing the classpath and update pom.xml to 4.2 for diirt module

### PR DESCRIPTION
**Pull request by shroffk**

### CODE REVIEW

**Comment by kasemir** [comment]
I still get a diirt 4.2 related error:
````
[ERROR]   The project org.csstudio:org.csstudio.core.diirt.feature:0.0.1-SNAPSHOT (/home/ky9/git/cs-studio/core/diirt/diirt-features/org.csstudio.core.diirt.feature/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM: Could not find artifact org.csstudio:diirt-features:pom:4.1.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 3, column 11 -> [Help 2]
[ERROR]   
[ERROR]   The project org.csstudio:diirt-repository:4.1.0 (/home/ky9/git/cs-studio/core/diirt/diirt-repository/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM: Could not find artifact org.csstudio:diirt:pom:4.1.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 4, column 13 -> [Help 2]
````

The org.csstudio.core.diirt.feature/pom.xml indeed still looks for a parent pom 4.1, while 
core/pom.xml, core/diirt/pom.xml, core/diirt/diirt-features/pom.xml all use version 4.2.0-SNAPSHOT.

**Comment by shroffk** [comment]
I just wanted to update the parent version.
I guess I should just use maven to update all the versions.

**Comment by shroffk** [comment]
@kasemir Adding a fix into the latest pull request

**Comment by kasemir** [comment]
Go ahead and merge that whenever you're done.

**Comment by shroffk** [comment]
Done

**Comment by berryma4** [comment]
#1377

**Pull request merged**
