### PR TITLE
Change default property of fonts in *GraphModel classes.

### PR DESCRIPTION
**Pull request by ayemos**
So that there's less hard coded stuff and resolved issue about font name
displayed on property perspective.

### CODE REVIEW

**Comment by berryma4** [comment]
Is there an open issue for this?

**Comment by ayemos** [comment]
This bug-fix refers to this issue. #886

**Comment by berryma4** [comment]
@shroffk

**Comment by kasemir** [comment]
This is good. `MediaService.DEFAULT_BOLD_FONT` is really the macro `Default Bold`, much better than "Arial 12 Bold".

**Comment by berryma4** [comment]
yes, ... but some people's screens will look different?

**Comment by kasemir** [comment]
On Linux, when I create a new IntensityGraph, the X axis title font starts out as  "1|Arial|9.0|1|GTK|1".
.. but I don't have any Arial on that system, so it displays with a default font.
With this fix, DEFAULT_BOLD would be a change, but actually closer to the originally intended FontData("Arial", 9, SWT.BOLD).

I understand that people who aligned their displays to the pixel won't like it, but going forward I think we need to concentrate on compatibility based on functionality, not looks.
Labels will show the same text, text updates will show the same PV name, alarm sensitive widgets will remain alarm sensitive. The look of a Meter, the axis of a plot, the exact alarm-sensitive behaviour won't remain exactly the same.

**Pull request merged**
