### PR TITLE
Fail the build on whitespace violations.

### PR DESCRIPTION
**Pull request by willrogers**
You don't have to merge this - I'm just trying to prove that this will fail the Travis build.

Assuming there are some violations...

### CODE REVIEW

**Comment by willrogers** [comment]
Like that ...

**Comment by willrogers** [comment]
Now I'll fix the violations.

**Comment by willrogers** [comment]
See discussion at https://github.com/diirt/diirt/pull/70

**Comment by willrogers** [comment]
Ironic.  Failed because of trailing whitespace in `checkstyle-output.xml`.

**Comment by berryma4** [comment]
thank you!

**Comment by berryma4** [comment]
Kind of annoying, why does tycho surefire return 0 when tests fail?
I added this line because it doesn't, so I can check:
https://github.com/ControlSystemStudio/cs-studio/blob/master/build/travis.sh#L16

**Comment by willrogers** [comment]
Is it just this?

https://github.com/ControlSystemStudio/cs-studio/blob/master/core/pom.xml#L398

**Comment by berryma4** [comment]
hilarious!  I should have grep'ed instead of trusting my eyes :)

**Pull request merged**
