### PR TITLE
Adding Fault application to logbook module

### PR DESCRIPTION
**Pull request by shroffk**
Creating a new branch in the main ControlSystemStudio repo itself to understand the failure of the #2075 PR

### CODE REVIEW

**Comment by shroffk** [comment]
@berryma4 PR from the main repo seems to work fine. Although I strongly dislike this workflow.

I would prefer to understand why PR from my fork seems to be triggering cloning ControlSystemStudio branches.

I have not had this issue before and as far as I am aware there have been no changes in my setup or configuration.

This was my first PR on the newly created 4.5 master branch.

**Comment by willrogers** [comment]
The other Travis builds are running now.  Did someone do something?

**Comment by shroffk** [comment]
I see the slowdown
I simply created this PR.

**Comment by berryma4** [comment]
Maybe this was a TravisCI issue?  (Because the other builds, from your fork, are working now)
Did anyone do anything?

**Comment by shroffk** [comment]
Argh

**Comment by willrogers** [comment]
I think Eric just merged this three times in a row, but probably no harm done.

My guess is that this was a bug in Travis that they fixed.

**Comment by berryma4** [comment]
I only merged the one.   But, Github doesn't know the difference between pull request.  It considers it merged if the commits are merged (like how you can merge a pull request from command line, and push to master).

**Comment by willrogers** [comment]
Oh of course I hadn't thought of that.  Sorry for questioning your merging strategy!

**Pull request merged**
