### PR TITLE
Build/scan_dependencies.py correction

### PR DESCRIPTION
**Pull request by jbobnar**
Some changes in the build/scan_dependencies.py script.

@matthieulambertiter please provide a comment, what this change was about.

### CODE REVIEW

**Comment by berryma4** [comment]
@shroffk owns the script

**Comment by shroffk** [comment]
I am sorry it has been awhile, can you explain the need for the change?
I see the mmap import but not sure where it is used.

**Comment by matthieulambertiter** [comment]
The import of mmap is a mistake. The build on my side was not working anymore, i was not able to found the dependencies.

**Comment by berryma4** [comment]
@shroffk okay?

**Pull request merged**
