### PR TITLE
o.c.phoebus.integration: find empty port, find phoebus in user path

### PR DESCRIPTION
**Pull request by berryma4**
#2607

### CODE REVIEW

**Comment by berryma4** [comment]
I think we could probably organize this set of plugins different. But, to start I wanted to loosen the coupling a bit (ie. needing a version, port number, etc.)

**Comment by shroffk** [comment]
I have a set of changes that I need to make for the phoebus integration...
however I am stuck with the previously mentions issues with running cs-studio in eclipse.

**Comment by berryma4** [comment]
I see the same issue (batik). It looks like a split package resolving issue.

**Comment by shroffk** [comment]
Is everyone able to successfully run/debug cs-studio from inside cs-studio?

**Comment by kasemir** [comment]
I like the idea of having the integration plugin pick a port, so each Eclipse instance interfaces with its own phoebus instance.

But related to the eclipse issues: All the recent pull requests were merged with failing travis builds. Can anybody build and run this stuff?

**Comment by berryma4** [comment]
The travis builds are timing out. If we email they usually extend it. It does take longer to build with this version of tycho, it is fix in 1.4, but it has other issues ....

**Comment by kasemir** [comment]
My eclipse setup is based on sources from March, the "java8" branch.
For some reason, maven doesn't build with the java8 branch.
So since March I have no local CS-Studio updates because both building the old branch with Java 8 and working on the 'master' with Java 9/10/11/12 is broken.

**Comment by shroffk** [comment]
I can build it on my CI server
I can build it on the command line on my machine

I can't get it to run properly inside the IDE...
https://github.com/ControlSystemStudio/cs-studio/pull/2601#issuecomment-512957155

I know this is specifically an IDE issue cause the product I build runs fine. It resolves batik and the rest of the dependency chain fine.

However, not having things working in the IDE really makes it difficult to develop... after 2 days of trying to understand why eclipse **alone** does not like how the dependencies are sorted I switched to another task.

**Comment by kasemir** [comment]
Why are the travis builds still failing when the maven build otherwise works for you?

**Comment by shroffk** [comment]
like eric said...this has something to do with the travis infrastructure/resource and build duration

**Comment by shroffk** [comment]
I have actually not had much trouble getting it to build...but getting it to properly run inside the IDE for development purposes is something I still can't get to work.

**Comment by berryma4** [comment]
@shroffk you should be okay now, after #2609

**Comment by berryma4** [comment]
@shroffk  could we merge this?

**Comment by berryma4** [comment]
thank you!

**Pull request merged**
