### PR TITLE
SaveRestore Git repository change (#1926)

### PR DESCRIPTION
**Pull request by jbobnar**
Fixes the issue #1926 

I also made some minor logging improvements, and updated the build properties to use target/classes instead of bin/ as output folder (this is forced by maven and was introduced when the .project and .classpath files were removed).

### CODE REVIEW

**Comment by berryma4** [comment]
It seems you have some checkstyle errors:
```java
/home/travis/build/ControlSystemStudio/cs-studio/applications/saverestore/saverestore-plugins/org.csstudio.saverestore.git/src/org/csstudio/saverestore/git/GitManager.java:179: error: Trailing whitespaces
/home/travis/build/ControlSystemStudio/cs-studio/applications/saverestore/saverestore-plugins/org.csstudio.saverestore.test/src/org/csstudio/saverestore/UtilitiesTest.java:25:1: warning: Redundant import from the same package - org.csstudio.saverestore.Utilities.
/home/travis/build/ControlSystemStudio/cs-studio/applications/saverestore/saverestore-plugins/org.csstudio.saverestore.ui/src/org/csstudio/saverestore/ui/SnapshotViewerController.java:634: error: Trailing whitespaces
/home/travis/build/ControlSystemStudio/cs-studio/applications/saverestore/saverestore-plugins/org.csstudio.saverestore/src/org/csstudio/saverestore/SaveRestoreService.java:287: error: Trailing whitespaces
/home/travis/build/ControlSystemStudio/cs-studio/applications/saverestore/saverestore-plugins/org.csstudio.saverestore/src/org/csstudio/saverestore/SaveRestoreService.java:289: error: Trailing whitespaces
/home/travis/build/ControlSystemStudio/cs-studio/applications/saverestore/saverestore-plugins/org.csstudio.saverestore/src/org/csstudio/saverestore/SaveRestoreService.java:295: error: Trailing whitespaces
/home/travis/build/ControlSystemStudio/cs-studio/applications/saverestore/saverestore-plugins/org.csstudio.saverestore/src/org/csstudio/saverestore/SaveRestoreService.java:298: error: Trailing whitespaces
/home/travis/build/ControlSystemStudio/cs-studio/applications/saverestore/saverestore-plugins/org.csstudio.saverestore/src/org/csstudio/saverestore/SaveRestoreService.java:300: error: Trailing whitespaces
/home/travis/build/ControlSystemStudio/cs-studio/applications/saverestore/saverestore-plugins/org.csstudio.saverestore/src/org/csstudio/saverestore/SaveRestoreService.java:313: error: Trailing whitespaces
/home/travis/build/ControlSystemStudio/cs-studio/applications/saverestore/saverestore-plugins/org.csstudio.saverestore/src/org/csstudio/saverestore/SaveRestoreService.java:319: error: Trailing whitespaces
```

**Comment by jbobnar** [comment]
Sorry for that. New workspace and forgot to configure the exit actions.

I removed all trailing white spaces, but I need some instructions about the "Redundant import warning".
The test classes are in the fragment plugin and are located in the same "package name" as the host plugin code. They have to import the classes from the host plugin, otherwise there is a compilation code. Is there a CSS wide naming convention for the unit tests package names?

**Comment by berryma4** [comment]
Strange, it should be the same package name as the host.

**Comment by jbobnar** [comment]
I turned the imports around a bit. It should be OK now.

I noticed there are two other warnings of the same type in the travis output: one in the ImageTest and one im VTypeHelperTest.

**Comment by berryma4** [comment]
Thank you!

**Pull request merged**
