### PR TITLE
Updated references to Jython ver. 2.7.1.

### PR DESCRIPTION
**Pull request by claudio-rosati**
[#74](https://github.com/ControlSystemStudio/maven-osgi-bundles/pull/74) is required first.

### CODE REVIEW

**Comment by kasemir** [comment]
Fails with "Missing requirement: org.csstudio.scan.server 4.4.0.qualifier requires 'bundle org.python.jython 2.7.1' but it could not be found". 
https://github.com/ControlSystemStudio/maven-osgi-bundles/pull/74 has been merged which adds 2.7.1 to the maven-osgi-bundles, so I don't understand this error.

**Comment by claudio-rosati** [comment]
Yes, strange because I don't have it

**Comment by kasemir** [comment]
I think when you build locally, you use what's in the maven-osgi-bundles/master.
This travis build downloads some copy of maven-osgi-bundles from an update site, and that's not been updated.

**Comment by claudio-rosati** [comment]
That's weird.

**Comment by claudio-rosati** [comment]
@kasemir @berryma4 
Looking at the raw log, i see the following at the end:

```
The job exceeded the maximum log length, and has been terminated.
```

**Comment by berryma4** [comment]
https://github.com/travis-ci/travis-ci/issues/1382

I'll look at quieting the download parts for Tycho, that might help.

**Comment by berryma4** [comment]
Switching to ```mvn --batch-mode ...``` might help

**Comment by claudio-rosati** [comment]
Thank you Eric.

**Comment by berryma4** [comment]
Batch might help, but we may need ```grep -v ``` a few things too. ie. The word "Downloading".

**Comment by claudio-rosati** [comment]
@berryma4 
Probably you need to add also `-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn` to the maven options

**Comment by claudio-rosati** [comment]
Found here: https://blogs.itemis.com/en/in-a-nutshell-removing-artifact-messages-from-maven-log-output

**Comment by berryma4** [comment]
You should be able to merge the fix from master now.

**Comment by claudio-rosati** [comment]
@berryma4 
It worked, thank you.
Can you please merge it?

**Comment by claudio-rosati** [comment]
Thank you

**Comment by claudio-rosati** [comment]
@kasemir 
Can you now merge [#453](https://github.com/kasemir/org.csstudio.display.builder/pull/453) please?

**Pull request merged**
