### PR TITLE
Quickfix for PvManager vImage

### PR DESCRIPTION
**Pull request by css-iter**

### CODE REVIEW

**Comment by berryma4** [comment]
please reference issue ticket

**Comment by kasemir** [comment]
The travis build shows
````
[INFO] applications-p2repo ................................ SUCCESS [  0.050 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
````
but then still has an error somewhere. Can anybody spot the error in the travis check?

We need to merge this, because otherwise right now the 'master' build is broken in `org.csstudio.utility.pvmanager.ui`.

Note that all of this requires building with diirt/diirt, not ControlSystemStudio/diirt.
diirt/diirt has the updated VImage, ControlSystemStudio/diirt is to be deprecated, right, @shroffk ?

**Comment by berryma4** [comment]
core has an error:
https://travis-ci.org/ControlSystemStudio/cs-studio/builds/251035955#L1630
missing depends

**Comment by kasemir** [comment]
Good, you found it:
```
[ERROR]   Software being installed: org.csstudio.utility.pvmanager.ui 3.2.0.qualifier
[ERROR]   Missing requirement: org.csstudio.utility.pvmanager.ui 3.2.0.qualifier requires 'package org.diirt.util.array 3.1.6' but it could not be found
```

I don't see _that_ error in pvmanager.ui when I build core with diirt/diirt.
Instead, I see the compiler error in pvmanager.ui related to the updated VImage, the one that Borut is trying to fix with this pull request.

Is the travis build setup still using ControlSystemStudio/diirt instead of diirt/diirt?

**Comment by boryto** [comment]
The build uses http://diirt.download.controlsystemstudio.org/diirt/3.1.5/ -- https://travis-ci.org/ControlSystemStudio/cs-studio/builds/251035955#L1298
and 
http://download.controlsystemstudio.org/core/4.5/diirt/ -- https://travis-ci.org/ControlSystemStudio/cs-studio/builds/251035955#L1323

The org.diirt.util.array 3.1.6 is not in this repos, but this was added to the code 2 years ago. A guess it is not yet in the 3.1.5 release.

**Comment by kasemir** [comment]
Diirt as built from the master of https://github.com/diirt/diirt results in org.diirt.util 3.1.7.
Does diirt 3.1.6 need to be released? Or even 3.1.7?

**Comment by shroffk** [comment]
yes, 3.1.6 needs to be released...it was tagged for release however due some issues with the credentials it was not published
I am working with Eric on resolving this.

**Comment by shroffk** [comment]
The 3.1.7 was because of a release job on cloudbees which tagged and updated the version but failed to correctly push the repo.
when trying to debug the problem successive build (on cloudbees only) would randomly terminate (no errors or failed tests...the jvm would simply exit)

Based on @berryma4 s suggestion I am setting up travis to do future releases...In the mean while I released diirt 3.1.6 repo manually. It should be available now at http://diirt.download.controlsystemstudio.org/diirt/3.1.6

**Comment by kasemir** [comment]
Kunal released diirt 3.1.6. Trigger a rebuild of this, which should now succeed?

**Comment by shroffk** [comment]
Can you cherry pick the changes from the above PR

**Comment by kasemir** [comment]
Now this pull request is basically the same as #2236, so one of them needs to be merged, the other deleted

**Comment by shroffk** [comment]
yes, they are the same since I needed to test the build with the diirt 3.1.6 - we can merge one or the other.

**Comment by shroffk** [comment]
I have the #2236 CI builds succeeding...can we merge that and close this?
@kasemir @berryma4 @css-iter

**Comment by kasemir** [comment]
Yes!

**Comment by css-iter** [comment]
Ok, thank you.

**Pull request closed without merging**
