### PR TITLE
Linking container macros

### PR DESCRIPTION
**Pull request by jbobnar**
This adds the ability to specify the linking container opi_file with a macro as requested in #1656 

The opi_file can now be $(MyMacro).opi. If $(MyMacro) is defined in the linking container widget's hierarchy, the file name will be resolved before the linked opi is loaded.

### CODE REVIEW

**Comment by berryma4** [comment]
We have had a lot of macro pull request.  I'm holding off on all of them until next week (code a thon at BNL).  We need to add whatever the expected behavior to our opi regression test repo. 

https://github.com/ControlSystemStudio/opi-regression-tests

**Comment by berryma4** [comment]
Please merge master too this branch.  A Travis ci yml file was added for testing.

**Comment by NickeZ** [comment]
Will this fix also cover scripts or could this also be implemented?

```
2016-05-20 10:11:58 ERROR: Failed to register ${PREFIX}/test.js. 
java.io.FileNotFoundException: ${PREFIX}/test.js
```

It already seems to work for images.

**Comment by jbobnar** [comment]
@NickeZ it doesn't cover scripts. Only the the opi_file property is affected.

**Comment by berryma4** [comment]
I've added a test for this in the opi regression tests:
ControlSystemStudio/opi-regression-tests@eea64ac1db109f0f3842ed02bb71c13aa8458fbb
It's not obvious that the user needs to have the .opi extension for it to be accepted by the resource selector dialog (ie. ${MyMacro}.opi).

**Comment by berryma4** [comment]
@shroffk I'm merging, would you like to test also?
It passes what we have in https://github.com/ControlSystemStudio/opi-regression-tests

**Comment by berryma4** [comment]
@shroffk I do get a warning for your issue 1103 screen:
2016-06-16 10:23:40 WARNING: Infinite loop was detected when parsing the macro: PRI
But it does work.

**Pull request merged**
