### PR TITLE
Revert "Remove problematic javax.xml.jre plugin from build."

### PR DESCRIPTION
**Pull request by berryma4**
Reverts ControlSystemStudio/cs-studio#2105

### CODE REVIEW

**Comment by willrogers** [comment]
I think this has been happening for a little while.  Best guess: the change to cat the logs succeeds and returns zero.

**Comment by berryma4** [comment]
I might not need to revert.
@shroffk 's pull request had a bunch of whitespace errors:
https://api.travis-ci.org/jobs/202329020/log.txt?deansi=true

It seems we need to make this fail though.

**Comment by berryma4** [comment]
Made a pull request without the cat of the tests (only having the cat after fail)
https://github.com/ControlSystemStudio/cs-studio/pull/2108

**Comment by shroffk** [comment]
https://github.com/ControlSystemStudio/cs-studio/pull/2109

have fixed the whitespace error

**Comment by berryma4** [comment]
no need to revert.  problem was corrected in #2110

**Pull request closed without merging**
