### PR TITLE
Alarm Table Updates

### PR DESCRIPTION
**Pull request by jbobnar**
Implementation of the changes in the alarm table. Please review and if OK, I'll updated the help page and changelog. 

The major changes are: 
- multiple alarms table allowed (each can connect to a different configuration root): #1113 
- drag and drop items from the tree to the table to set a filter item: #1113 
- additional icons in the toolbar, to apply filter, select the entire root or show the tree root: #1113
- It is possible to configure the width, weight, title, and order or columns in the preferences: #1112 
- changing the width, order etc. in runtime will be preserved (for all tables): #1112 
- blinking icons of unacknowledged alarms (can be configured only via preferences) #1109 
- acknowledged and unacknowledged tables are synchronized (is the width of a column is changed or the columns are moved around, the other tables is updated accordingly)
- Added tooltips to all column headers
- Reorganized the alarm perspective to use perspective extensions instead of creating the layout programmatically.

### CODE REVIEW

**Comment by berryma4** [comment]
@kasemir can you check for merge.

**Comment by kasemir** [comment]
Yes.

**Comment by jbobnar** [comment]
Implemented blinking synchronisation across all tables.
Filtering of alarms happens on a non GUI thread.
Updated changelog.

**Comment by berryma4** [comment]
Can I close #1113, #1112, #1109 ?

**Pull request merged**
